// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SingleCuKernelController(	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
  input         clock,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
                reset,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
  output        io_kernel_ready,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_kernel_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input  [31:0] io_kernel_bits_kernelPc,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_kernargAddress,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_gridSize_0,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_gridSize_1,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_gridSize_2,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input  [15:0] io_kernel_bits_localSize_0,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_localSize_1,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_kernel_bits_localSize_2,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_completion_ready,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output        io_completion_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_completion_bits_success,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input  [3:0]  io_activeWarps,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_scalarInitialize_ready,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output        io_scalarInitialize_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [1:0]  io_scalarInitialize_bits_warpId,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [4:0]  io_scalarInitialize_bits_rd,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [31:0] io_scalarInitialize_bits_data,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_vectorInitialize_ready,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output        io_vectorInitialize_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [1:0]  io_vectorInitialize_bits_warpId,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [31:0] io_vectorInitialize_bits_data_0,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_vectorInitialize_bits_data_1,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_vectorInitialize_bits_data_2,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
                io_vectorInitialize_bits_data_3,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_launch_ready,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output        io_launch_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [1:0]  io_launch_bits_warpId,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [31:0] io_launch_bits_startPc,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [3:0]  io_launch_bits_activeMask,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input         io_finish_valid,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  input  [1:0]  io_finish_bits,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output [3:0]  io_residentWarps,	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
  output        io_workgroupDispatchComplete	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:11:14
);

  wire        _initialize_io_task_ready;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  wire        _initialize_io_launch_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  wire [1:0]  _initialize_io_assignedWarpId_bits;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  wire        _initialize_io_launchedTask_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  wire        _initialize_io_launchedTask_bits_lastWarp;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  wire        _dispatch_io_warp_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [31:0] _dispatch_io_warp_bits_kernelPc;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [31:0] _dispatch_io_warp_bits_kernargAddress;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [15:0] _dispatch_io_warp_bits_localSize_0;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [15:0] _dispatch_io_warp_bits_localSize_1;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [15:0] _dispatch_io_warp_bits_localSize_2;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [31:0] _dispatch_io_warp_bits_groupId_0;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [31:0] _dispatch_io_warp_bits_groupId_1;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [31:0] _dispatch_io_warp_bits_groupId_2;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [47:0] _dispatch_io_warp_bits_localLinearBase;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire [3:0]  _dispatch_io_warp_bits_activeMask;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire        _dispatch_io_warp_bits_lastWarp;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire        _dispatch_io_warpCompletion_ready;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire        _dispatch_io_completion_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  reg  [3:0]  running;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:25:32
  reg         dispatchComplete;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:26:41
  wire [3:0]  _GEN = {2'h0, io_finish_bits};	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:38:17
  wire [3:0]  _finishResident_T = running >> _GEN;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:25:32, :38:17
  wire        matchingFinish = io_finish_valid & _finishResident_T[0];	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:38:17, :39:65
  wire [3:0]  launchOH =
    io_launch_ready & _initialize_io_launch_valid
      ? 4'h1 << _initialize_io_assignedWarpId_bits
      : 4'h0;	// src/main/scala/chisel3/util/OneHot.scala:65:12, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34, :25:32, :43:29
  wire [3:0]  finishOH =
    _dispatch_io_warpCompletion_ready & matchingFinish ? 4'h1 << _GEN : 4'h0;	// src/main/scala/chisel3/util/OneHot.scala:65:12, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32, :25:32, :38:17, :39:65, :48:29
  always @(posedge clock) begin	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
    if (reset) begin	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      running <= 4'h0;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:25:32
      dispatchComplete <= 1'h0;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :26:41
    end
    else begin	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      if (|{launchOH, finishOH})	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:43:29, :48:29, :53:{17,21,33}
        running <= (running | launchOH) & ~finishOH;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:25:32, :43:29, :48:29, :54:{25,37,39}
      dispatchComplete <=
        ~(io_completion_ready & _dispatch_io_completion_valid)
        & (_initialize_io_launchedTask_valid & _initialize_io_launchedTask_bits_lastWarp
           | dispatchComplete);	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32, :24:34, :26:41, :56:{41,86}, :57:22, :59:28, :60:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
    initial begin	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
        running = _RANDOM[/*Zero width*/ 1'b0][3:0];	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :25:32
        dispatchComplete = _RANDOM[/*Zero width*/ 1'b0][4];	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :25:32, :26:41
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  KernelDispatchPipeline dispatch (	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .clock                         (clock),
    .reset                         (reset),
    .io_launch_ready               (io_kernel_ready),
    .io_launch_valid               (io_kernel_valid),
    .io_launch_bits_kernelPc       (io_kernel_bits_kernelPc),
    .io_launch_bits_kernargAddress (io_kernel_bits_kernargAddress),
    .io_launch_bits_gridSize_0     (io_kernel_bits_gridSize_0),
    .io_launch_bits_gridSize_1     (io_kernel_bits_gridSize_1),
    .io_launch_bits_gridSize_2     (io_kernel_bits_gridSize_2),
    .io_launch_bits_localSize_0    (io_kernel_bits_localSize_0),
    .io_launch_bits_localSize_1    (io_kernel_bits_localSize_1),
    .io_launch_bits_localSize_2    (io_kernel_bits_localSize_2),
    .io_warp_ready                 (_initialize_io_task_ready),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
    .io_warp_valid                 (_dispatch_io_warp_valid),
    .io_warp_bits_kernelPc         (_dispatch_io_warp_bits_kernelPc),
    .io_warp_bits_kernargAddress   (_dispatch_io_warp_bits_kernargAddress),
    .io_warp_bits_localSize_0      (_dispatch_io_warp_bits_localSize_0),
    .io_warp_bits_localSize_1      (_dispatch_io_warp_bits_localSize_1),
    .io_warp_bits_localSize_2      (_dispatch_io_warp_bits_localSize_2),
    .io_warp_bits_groupId_0        (_dispatch_io_warp_bits_groupId_0),
    .io_warp_bits_groupId_1        (_dispatch_io_warp_bits_groupId_1),
    .io_warp_bits_groupId_2        (_dispatch_io_warp_bits_groupId_2),
    .io_warp_bits_localLinearBase  (_dispatch_io_warp_bits_localLinearBase),
    .io_warp_bits_activeMask       (_dispatch_io_warp_bits_activeMask),
    .io_warp_bits_lastWarp         (_dispatch_io_warp_bits_lastWarp),
    .io_warpCompletion_ready       (_dispatch_io_warpCompletion_ready),
    .io_warpCompletion_valid       (matchingFinish),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:39:65
    .io_completion_ready           (io_completion_ready),
    .io_completion_valid           (_dispatch_io_completion_valid),
    .io_completion_bits_success    (io_completion_bits_success)
  );	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  wire        dispatch_io_warpCompletion_ready;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  assign dispatch_io_warpCompletion_ready = _dispatch_io_warpCompletion_ready;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
  WarpContextInitializer initialize (	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
    .clock                         (clock),
    .reset                         (reset),
    .io_task_ready                 (_initialize_io_task_ready),
    .io_task_valid                 (_dispatch_io_warp_valid),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_kernelPc         (_dispatch_io_warp_bits_kernelPc),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_kernargAddress   (_dispatch_io_warp_bits_kernargAddress),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_localSize_0      (_dispatch_io_warp_bits_localSize_0),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_localSize_1      (_dispatch_io_warp_bits_localSize_1),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_localSize_2      (_dispatch_io_warp_bits_localSize_2),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_groupId_0        (_dispatch_io_warp_bits_groupId_0),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_groupId_1        (_dispatch_io_warp_bits_groupId_1),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_groupId_2        (_dispatch_io_warp_bits_groupId_2),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_localLinearBase  (_dispatch_io_warp_bits_localLinearBase),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_activeMask       (_dispatch_io_warp_bits_activeMask),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_task_bits_lastWarp         (_dispatch_io_warp_bits_lastWarp),	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:23:32
    .io_activeWarps                (io_activeWarps),
    .io_scalar_ready               (io_scalarInitialize_ready),
    .io_scalar_valid               (io_scalarInitialize_valid),
    .io_scalar_bits_warpId         (io_scalarInitialize_bits_warpId),
    .io_scalar_bits_rd             (io_scalarInitialize_bits_rd),
    .io_scalar_bits_data           (io_scalarInitialize_bits_data),
    .io_vector_ready               (io_vectorInitialize_ready),
    .io_vector_valid               (io_vectorInitialize_valid),
    .io_vector_bits_warpId         (io_vectorInitialize_bits_warpId),
    .io_vector_bits_data_0         (io_vectorInitialize_bits_data_0),
    .io_vector_bits_data_1         (io_vectorInitialize_bits_data_1),
    .io_vector_bits_data_2         (io_vectorInitialize_bits_data_2),
    .io_vector_bits_data_3         (io_vectorInitialize_bits_data_3),
    .io_launch_ready               (io_launch_ready),
    .io_launch_valid               (_initialize_io_launch_valid),
    .io_launch_bits_warpId         (io_launch_bits_warpId),
    .io_launch_bits_startPc        (io_launch_bits_startPc),
    .io_launch_bits_activeMask     (io_launch_bits_activeMask),
    .io_assignedWarpId_bits        (_initialize_io_assignedWarpId_bits),
    .io_launchedTask_valid         (_initialize_io_launchedTask_valid),
    .io_launchedTask_bits_lastWarp (_initialize_io_launchedTask_bits_lastWarp)
  );	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:24:34
  assign io_completion_valid = _dispatch_io_completion_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :23:32
  assign io_launch_valid = _initialize_io_launch_valid;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :24:34
  assign io_residentWarps = running;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :25:32
  assign io_workgroupDispatchComplete = dispatchComplete;	// src/main/scala/opengpu/dispatch/SingleCuKernelController.scala:10:7, :26:41
endmodule

