// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Sv32PageTableWalker(	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
  input  clock,	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
         reset,	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
  output io_request_ready,	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:23:14
  input  io_request_valid,	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:23:14
         io_response_ready,	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:23:14
  output io_response_valid	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:23:14
);

  reg  [1:0] state;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30
  wire       io_request_ready_0 = state == 2'h0;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :45:29, :118:11
  always @(posedge clock) begin	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
    if (reset)	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
      state <= 2'h0;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :118:11
    else if (io_response_ready & (&state))	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :46:30
      state <= 2'h0;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :118:11
    else if (state == 2'h1)	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :48:35
      state <= 2'h2;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :50:36
    else if (io_request_ready_0 & io_request_valid)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:45:29
      state <= 2'h1;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:34:30, :48:35
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
    initial begin	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
        state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7, :34:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_request_ready = io_request_ready_0;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7, :45:29
  assign io_response_valid = &state;	// src/main/scala/opengpu/core/memory/Sv32PageTableWalker.scala:22:7, :34:30, :46:30
endmodule

