// Generated by CIRCT firtool-1.133.0
module WarpSystemControl(	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  output        io_in_ready,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input         io_in_valid,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input  [31:0] io_in_bits_decode_pc,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input  [1:0]  io_in_bits_decode_warpId,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input  [3:0]  io_in_bits_decode_activeMask,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input         io_in_bits_decode_decoded_fence,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
                io_in_bits_decode_decoded_barrier,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
                io_in_bits_decode_decoded_join,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
                io_in_bits_decode_decoded_cease,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output        io_finish_valid,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [1:0]  io_finish_bits,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input         io_restore_ready,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output        io_restore_valid,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [1:0]  io_restore_bits,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input         io_resume_ready,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output        io_resume_valid,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [1:0]  io_resume_bits_warpId,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [31:0] io_resume_bits_pc,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [3:0]  io_resume_bits_activeMask,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  input         io_barrier_ready,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output        io_barrier_valid,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [1:0]  io_barrier_bits_warpId,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [31:0] io_barrier_bits_pc,	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
  output [3:0]  io_barrier_bits_activeMask	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:16:14
);

  wire [31:0] _io_barrier_bits_pc_T = io_in_bits_decode_pc + 32'h4;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:46:45
  assign io_in_ready =
    io_in_bits_decode_decoded_cease
    | (io_in_bits_decode_decoded_join
         ? io_restore_ready
         : io_in_bits_decode_decoded_fence
             ? io_resume_ready
             : ~io_in_bits_decode_decoded_barrier | io_barrier_ready);	// src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_finish_valid = io_in_valid & io_in_bits_decode_decoded_cease;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :38:34
  assign io_finish_bits = io_in_bits_decode_warpId;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_restore_valid = io_in_valid & io_in_bits_decode_decoded_join;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :41:35
  assign io_restore_bits = io_in_bits_decode_warpId;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_resume_valid = io_in_valid & io_in_bits_decode_decoded_fence;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :44:34
  assign io_resume_bits_warpId = io_in_bits_decode_warpId;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_resume_bits_pc = _io_barrier_bits_pc_T;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :46:45
  assign io_resume_bits_activeMask = io_in_bits_decode_activeMask;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_barrier_valid = io_in_valid & io_in_bits_decode_decoded_barrier;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :49:35
  assign io_barrier_bits_warpId = io_in_bits_decode_warpId;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
  assign io_barrier_bits_pc = _io_barrier_bits_pc_T;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7, :46:45
  assign io_barrier_bits_activeMask = io_in_bits_decode_activeMask;	// src/main/scala/opengpu/core/system/WarpSystemControl.scala:15:7
endmodule

