// Generated by CIRCT firtool-1.133.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module InstructionTlb_Verification_Assert();	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
  `ifndef SYNTHESIS	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
    always @(posedge InstructionTlb.clock) begin	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:14:7, :140:11
      if (InstructionTlb.io_flush_valid & ~InstructionTlb.reset
          & ~(InstructionTlb._io_in_ready_T_3
              & InstructionTlb._io_pageWalkResponse_ready_T_1
              & InstructionTlb._io_physicalResponse_ready_T)) begin	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:14:7, :20:14, :67:8, :71:36, :76:18, :140:{11,23,39}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
          $error("Assertion failed: ITLB flush requires no pending translation\n");	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
        if (`STOP_COND_)	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
          $fatal;	// src/main/scala/opengpu/core/memory/InstructionTlb.scala:140:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

