// Generated by CIRCT firtool-1.133.0
`ifndef layers_CopyEngine_1_Verification_Assert	// src/main/scala/opengpu/dma/CopyEngine.scala:41:7
  `define layers_CopyEngine_1_Verification_Assert
  `include "layers-CopyEngine_1-Verification.sv"	// src/main/scala/opengpu/dma/CopyEngine.scala:41:7
  bind CopyEngine_1 CopyEngine_1_Verification_Assert verification_assert ();
`endif // not def layers_CopyEngine_1_Verification_Assert
