// Generated by CIRCT firtool-1.133.0
`ifndef layers_VectorFcvtAlu_Verification_Assert	// src/main/scala/opengpu/core/vector/VectorFcvtAlu.scala:23:7
  `define layers_VectorFcvtAlu_Verification_Assert
  `include "layers-VectorFcvtAlu-Verification.sv"	// src/main/scala/opengpu/core/vector/VectorFcvtAlu.scala:23:7
  bind VectorFcvtAlu VectorFcvtAlu_Verification_Assert verification_assert ();
`endif // not def layers_VectorFcvtAlu_Verification_Assert
