// Generated by CIRCT firtool-1.133.0
`ifndef layers_GpuSystem_Verification_Cover	// src/main/scala/opengpu/system/GpuSystem.scala:48:7
  `define layers_GpuSystem_Verification_Cover
  `include "layers-GpuSystem-Verification.sv"	// src/main/scala/opengpu/system/GpuSystem.scala:48:7
`endif // not def layers_GpuSystem_Verification_Cover
