// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SimtBranchStackSequencer(	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
  input         clock,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
                reset,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
  output        io_in_ready,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input         io_in_valid,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [1:0]  io_in_bits_warpId,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [31:0] io_in_bits_currentPc,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [3:0]  io_in_bits_currentMask,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input         io_in_bits_hasAlternate,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [31:0] io_in_bits_alternate_pc,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [3:0]  io_in_bits_alternate_activeMask,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input         io_in_bits_hasReconvergence,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [31:0] io_in_bits_reconvergence_pc,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input  [3:0]  io_in_bits_reconvergence_activeMask,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
                io_freeEntries,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  input         io_stackPush_ready,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output        io_stackPush_valid,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output [31:0] io_stackPush_bits_pc,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output [3:0]  io_stackPush_bits_activeMask,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output        io_current_valid,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output [1:0]  io_current_bits_warpId,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output [31:0] io_current_bits_pc,	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
  output [3:0]  io_current_bits_activeMask	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:20:14
);

  reg  [1:0]  state;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:29:30
  reg  [1:0]  saved_warpId;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [31:0] saved_currentPc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [3:0]  saved_currentMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg         saved_hasAlternate;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [31:0] saved_alternate_pc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [3:0]  saved_alternate_activeMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [31:0] saved_reconvergence_pc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  reg  [3:0]  saved_reconvergence_activeMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
  wire        io_in_ready_0 =
    state == 2'h0
    & io_freeEntries >= {2'h0,
                         {1'h0, io_in_bits_hasReconvergence}
                           + {1'h0, io_in_bits_hasAlternate}};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :33:40, :35:{11,20,38}
  wire        _io_stackPush_bits_T = state == 2'h1;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :38:11
  wire        _io_stackPush_valid_T_1 = state == 2'h2;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :38:42
  wire        io_stackPush_valid_0 = _io_stackPush_bits_T | _io_stackPush_valid_T_1;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:38:{11,33,42}
  wire        _GEN = io_stackPush_ready & io_stackPush_valid_0;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:38:33
  wire        _GEN_0 = io_in_ready_0 & io_in_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:35:20, :47:23
  always @(posedge clock) begin	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
    if (reset)	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
      state <= 2'h0;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30
    else if (&state)	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:29:30, :42:29
      state <= 2'h0;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30
    else if (_io_stackPush_valid_T_1 & _GEN)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:38:42, :62:32
      state <= 2'h3;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30
    else if (_io_stackPush_bits_T & _GEN)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:38:11, :58:36
      state <= {1'h1, ~saved_hasAlternate};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:29:30, :30:26, :59:17
    else if (_GEN_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:47:23
      state <= io_in_bits_hasReconvergence ? 2'h1 : {1'h1, ~io_in_bits_hasAlternate};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :49:39, :50:13, :51:41, :52:13, :54:13
    if (_GEN_0) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:47:23
      saved_warpId <= io_in_bits_warpId;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_currentPc <= io_in_bits_currentPc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_currentMask <= io_in_bits_currentMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_hasAlternate <= io_in_bits_hasAlternate;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_alternate_pc <= io_in_bits_alternate_pc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_alternate_activeMask <= io_in_bits_alternate_activeMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_reconvergence_pc <= io_in_bits_reconvergence_pc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
      saved_reconvergence_activeMask <= io_in_bits_reconvergence_activeMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:30:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
    initial begin	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
        end	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
        state = _RANDOM[2'h0][1:0];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30
        saved_warpId = _RANDOM[2'h0][3:2];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :30:26
        saved_currentPc = {_RANDOM[2'h0][31:4], _RANDOM[2'h1][3:0]};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :30:26
        saved_currentMask = _RANDOM[2'h1][7:4];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
        saved_hasAlternate = _RANDOM[2'h1][9];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
        saved_alternate_pc = {_RANDOM[2'h1][31:10], _RANDOM[2'h2][9:0]};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
        saved_alternate_activeMask = _RANDOM[2'h2][13:10];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
        saved_reconvergence_pc = {_RANDOM[2'h2][31:20], _RANDOM[2'h3][19:0]};	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
        saved_reconvergence_activeMask = _RANDOM[2'h3][23:20];	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = io_in_ready_0;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :35:20
  assign io_stackPush_valid = io_stackPush_valid_0;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :38:33
  assign io_stackPush_bits_pc =
    _io_stackPush_bits_T ? saved_reconvergence_pc : saved_alternate_pc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26, :38:11, :40:8
  assign io_stackPush_bits_activeMask =
    _io_stackPush_bits_T ? saved_reconvergence_activeMask : saved_alternate_activeMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26, :38:11, :40:8
  assign io_current_valid = &state;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :29:30, :42:29
  assign io_current_bits_warpId = saved_warpId;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
  assign io_current_bits_pc = saved_currentPc;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
  assign io_current_bits_activeMask = saved_currentMask;	// src/main/scala/opengpu/core/execute/control/SimtBranchStackSequencer.scala:16:7, :30:26
endmodule

