// Generated by CIRCT firtool-1.133.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module VectorFmaAlu_Verification_Assert();	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:163:11
  `ifndef SYNTHESIS	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:158:11
    wire _GEN = VectorFmaAlu.io_in_valid & ~VectorFmaAlu.reset;	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:23:7, :24:14, :158:11
    always @(posedge VectorFmaAlu.clock) begin	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:23:7, :158:11
      if (_GEN
          & ~(VectorFmaAlu.io_in_bits_operandType == 3'h1
              | VectorFmaAlu.io_in_bits_operandType == 3'h5)) begin	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:23:7, :24:14, :38:46, :158:11, :159:{30,43}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:158:11
          $error("Assertion failed: VectorFmaAlu currently supports FVV and FVF operand forms only\n");	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:158:11
        if (`STOP_COND_)	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:158:11
          $fatal;	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:158:11
      end
      if (_GEN & ~VectorFmaAlu.isSupported) begin	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:23:7, :47:63, :163:11
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:163:11
          $error("Assertion failed: VectorFmaAlu received an unsupported funct6\n");	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:163:11
        if (`STOP_COND_)	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:163:11
          $fatal;	// src/main/scala/opengpu/core/vector/VectorFmaAlu.scala:163:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

