// Generated by CIRCT firtool-1.133.0
`ifndef layers_NearClipStage_Verification	// src/main/scala/opengpu/graphics/NearClipStage.scala:36:7
  `define layers_NearClipStage_Verification
  bind NearClipStage NearClipStage_Verification verification ();
`endif // not def layers_NearClipStage_Verification
