// Generated by CIRCT firtool-1.133.0
`ifndef layers_FpuIssueStage_Verification_Assert	// src/main/scala/opengpu/core/backend/issue/FpuIssueStage.scala:24:7
  `define layers_FpuIssueStage_Verification_Assert
  `include "layers-FpuIssueStage-Verification.sv"	// src/main/scala/opengpu/core/backend/issue/FpuIssueStage.scala:24:7
  bind FpuIssueStage FpuIssueStage_Verification_Assert verification_assert ();
`endif // not def layers_FpuIssueStage_Verification_Assert
