// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenderCore(	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
  input         clock,	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
                reset,	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
  input  [31:0] io_cmdBase,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [15:0] io_cmdCount,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_start,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_cbMem_req_ready,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_cbMem_req_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output [31:0] io_cbMem_req_bits_addr,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_cbMem_resp_ready,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_cbMem_resp_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_cbMem_resp_bits_data,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_fbMem_req_ready,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_fbMem_req_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_fbMem_req_bits_write,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output [31:0] io_fbMem_req_bits_addr,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_fbMem_req_bits_data,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_fbMem_resp_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_fbMem_resp_bits_data,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_fbMem_resp_bits_write,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_fbMem_resp_bits_addr,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_colorBase,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_depthBase,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_stride,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_texEnable,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_texBase,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [13:0] io_texWidth,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_texHeight,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_texWrapClamp,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
                io_depthTestEnable,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [2:0]  io_depthFunc,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_depthWriteEnable,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [1:0]  io_cullMode,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_texMem_req_ready,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_texMem_req_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output [31:0] io_texMem_req_bits_addr,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_texMem_resp_ready,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_texMem_resp_valid,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_texMem_resp_bits_data,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input         io_texMem_resp_bits_write,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  input  [31:0] io_texMem_resp_bits_addr,	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
  output        io_done	// src/main/scala/opengpu/graphics/RenderCore.scala:41:14
);

  wire        _rp_io_draw_ready;	// src/main/scala/opengpu/graphics/RenderCore.scala:87:26
  wire        _rp_io_done;	// src/main/scala/opengpu/graphics/RenderCore.scala:87:26
  wire        _cb_io_draw_valid;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_0_x;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_0_y;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_0_z;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_0_w;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_1_x;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_1_y;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_1_z;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_1_w;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_2_x;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_2_y;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_2_z;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_clip_2_w;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_0_r;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_0_g;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_0_b;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_1_r;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_1_g;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_1_b;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_2_r;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_2_g;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [7:0]  _cb_io_draw_bits_color_2_b;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_depth_0;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_depth_1;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_depth_2;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_0_u;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_0_v;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_1_u;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_1_v;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_2_u;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [31:0] _cb_io_draw_bits_uv_2_v;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_stateOverride;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_depthTestEnable;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [2:0]  _cb_io_draw_bits_depthFunc;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_depthWriteEnable;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_blendEnable;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire [1:0]  _cb_io_draw_bits_cullMode;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_texEnable;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_draw_bits_texWrapClamp;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  wire        _cb_io_done;	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  reg         startDelay;	// src/main/scala/opengpu/graphics/RenderCore.scala:91:35
  always @(posedge clock) begin	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
    if (reset)	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      startDelay <= 1'h0;	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7, :91:35
    else	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      startDelay <= io_start;	// src/main/scala/opengpu/graphics/RenderCore.scala:91:35
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
    initial begin	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
        startDelay = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7, :91:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CommandBufferStage cb (	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .clock                         (clock),
    .reset                         (reset),
    .io_base                       (io_cmdBase),
    .io_count                      (io_cmdCount),
    .io_start                      (startDelay),	// src/main/scala/opengpu/graphics/RenderCore.scala:91:35
    .io_mem_req_ready              (io_cbMem_req_ready),
    .io_mem_req_valid              (io_cbMem_req_valid),
    .io_mem_req_bits_addr          (io_cbMem_req_bits_addr),
    .io_mem_resp_ready             (io_cbMem_resp_ready),
    .io_mem_resp_valid             (io_cbMem_resp_valid),
    .io_mem_resp_bits_data         (io_cbMem_resp_bits_data),
    .io_draw_ready                 (_rp_io_draw_ready),	// src/main/scala/opengpu/graphics/RenderCore.scala:87:26
    .io_draw_valid                 (_cb_io_draw_valid),
    .io_draw_bits_clip_0_x         (_cb_io_draw_bits_clip_0_x),
    .io_draw_bits_clip_0_y         (_cb_io_draw_bits_clip_0_y),
    .io_draw_bits_clip_0_z         (_cb_io_draw_bits_clip_0_z),
    .io_draw_bits_clip_0_w         (_cb_io_draw_bits_clip_0_w),
    .io_draw_bits_clip_1_x         (_cb_io_draw_bits_clip_1_x),
    .io_draw_bits_clip_1_y         (_cb_io_draw_bits_clip_1_y),
    .io_draw_bits_clip_1_z         (_cb_io_draw_bits_clip_1_z),
    .io_draw_bits_clip_1_w         (_cb_io_draw_bits_clip_1_w),
    .io_draw_bits_clip_2_x         (_cb_io_draw_bits_clip_2_x),
    .io_draw_bits_clip_2_y         (_cb_io_draw_bits_clip_2_y),
    .io_draw_bits_clip_2_z         (_cb_io_draw_bits_clip_2_z),
    .io_draw_bits_clip_2_w         (_cb_io_draw_bits_clip_2_w),
    .io_draw_bits_color_0_r        (_cb_io_draw_bits_color_0_r),
    .io_draw_bits_color_0_g        (_cb_io_draw_bits_color_0_g),
    .io_draw_bits_color_0_b        (_cb_io_draw_bits_color_0_b),
    .io_draw_bits_color_1_r        (_cb_io_draw_bits_color_1_r),
    .io_draw_bits_color_1_g        (_cb_io_draw_bits_color_1_g),
    .io_draw_bits_color_1_b        (_cb_io_draw_bits_color_1_b),
    .io_draw_bits_color_2_r        (_cb_io_draw_bits_color_2_r),
    .io_draw_bits_color_2_g        (_cb_io_draw_bits_color_2_g),
    .io_draw_bits_color_2_b        (_cb_io_draw_bits_color_2_b),
    .io_draw_bits_depth_0          (_cb_io_draw_bits_depth_0),
    .io_draw_bits_depth_1          (_cb_io_draw_bits_depth_1),
    .io_draw_bits_depth_2          (_cb_io_draw_bits_depth_2),
    .io_draw_bits_uv_0_u           (_cb_io_draw_bits_uv_0_u),
    .io_draw_bits_uv_0_v           (_cb_io_draw_bits_uv_0_v),
    .io_draw_bits_uv_1_u           (_cb_io_draw_bits_uv_1_u),
    .io_draw_bits_uv_1_v           (_cb_io_draw_bits_uv_1_v),
    .io_draw_bits_uv_2_u           (_cb_io_draw_bits_uv_2_u),
    .io_draw_bits_uv_2_v           (_cb_io_draw_bits_uv_2_v),
    .io_draw_bits_stateOverride    (_cb_io_draw_bits_stateOverride),
    .io_draw_bits_depthTestEnable  (_cb_io_draw_bits_depthTestEnable),
    .io_draw_bits_depthFunc        (_cb_io_draw_bits_depthFunc),
    .io_draw_bits_depthWriteEnable (_cb_io_draw_bits_depthWriteEnable),
    .io_draw_bits_blendEnable      (_cb_io_draw_bits_blendEnable),
    .io_draw_bits_cullMode         (_cb_io_draw_bits_cullMode),
    .io_draw_bits_texEnable        (_cb_io_draw_bits_texEnable),
    .io_draw_bits_texWrapClamp     (_cb_io_draw_bits_texWrapClamp),
    .io_done                       (_cb_io_done)
  );	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
  RenderPipeline rp (	// src/main/scala/opengpu/graphics/RenderCore.scala:87:26
    .clock                         (clock),
    .reset                         (reset),
    .io_draw_ready                 (_rp_io_draw_ready),
    .io_draw_valid                 (_cb_io_draw_valid),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_0_x         (_cb_io_draw_bits_clip_0_x),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_0_y         (_cb_io_draw_bits_clip_0_y),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_0_z         (_cb_io_draw_bits_clip_0_z),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_0_w         (_cb_io_draw_bits_clip_0_w),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_1_x         (_cb_io_draw_bits_clip_1_x),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_1_y         (_cb_io_draw_bits_clip_1_y),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_1_z         (_cb_io_draw_bits_clip_1_z),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_1_w         (_cb_io_draw_bits_clip_1_w),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_2_x         (_cb_io_draw_bits_clip_2_x),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_2_y         (_cb_io_draw_bits_clip_2_y),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_2_z         (_cb_io_draw_bits_clip_2_z),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_clip_2_w         (_cb_io_draw_bits_clip_2_w),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_0_r        (_cb_io_draw_bits_color_0_r),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_0_g        (_cb_io_draw_bits_color_0_g),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_0_b        (_cb_io_draw_bits_color_0_b),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_1_r        (_cb_io_draw_bits_color_1_r),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_1_g        (_cb_io_draw_bits_color_1_g),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_1_b        (_cb_io_draw_bits_color_1_b),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_2_r        (_cb_io_draw_bits_color_2_r),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_2_g        (_cb_io_draw_bits_color_2_g),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_color_2_b        (_cb_io_draw_bits_color_2_b),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depth_0          (_cb_io_draw_bits_depth_0),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depth_1          (_cb_io_draw_bits_depth_1),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depth_2          (_cb_io_draw_bits_depth_2),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_0_u           (_cb_io_draw_bits_uv_0_u),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_0_v           (_cb_io_draw_bits_uv_0_v),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_1_u           (_cb_io_draw_bits_uv_1_u),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_1_v           (_cb_io_draw_bits_uv_1_v),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_2_u           (_cb_io_draw_bits_uv_2_u),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_uv_2_v           (_cb_io_draw_bits_uv_2_v),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_stateOverride    (_cb_io_draw_bits_stateOverride),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depthTestEnable  (_cb_io_draw_bits_depthTestEnable),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depthFunc        (_cb_io_draw_bits_depthFunc),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_depthWriteEnable (_cb_io_draw_bits_depthWriteEnable),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_blendEnable      (_cb_io_draw_bits_blendEnable),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_cullMode         (_cb_io_draw_bits_cullMode),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_texEnable        (_cb_io_draw_bits_texEnable),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_draw_bits_texWrapClamp     (_cb_io_draw_bits_texWrapClamp),	// src/main/scala/opengpu/graphics/RenderCore.scala:86:26
    .io_mem_req_ready              (io_fbMem_req_ready),
    .io_mem_req_valid              (io_fbMem_req_valid),
    .io_mem_req_bits_write         (io_fbMem_req_bits_write),
    .io_mem_req_bits_addr          (io_fbMem_req_bits_addr),
    .io_mem_req_bits_data          (io_fbMem_req_bits_data),
    .io_mem_resp_valid             (io_fbMem_resp_valid),
    .io_mem_resp_bits_data         (io_fbMem_resp_bits_data),
    .io_mem_resp_bits_write        (io_fbMem_resp_bits_write),
    .io_mem_resp_bits_addr         (io_fbMem_resp_bits_addr),
    .io_colorBase                  (io_colorBase),
    .io_depthBase                  (io_depthBase),
    .io_stride                     (io_stride),
    .io_depthTestEnable            (io_depthTestEnable),
    .io_depthFunc                  (io_depthFunc),
    .io_depthWriteEnable           (io_depthWriteEnable),
    .io_cullMode                   (io_cullMode),
    .io_texEnable                  (io_texEnable),
    .io_texBase                    (io_texBase),
    .io_texWidth                   (io_texWidth),
    .io_texHeight                  (io_texHeight),
    .io_texWrapClamp               (io_texWrapClamp),
    .io_texMem_req_ready           (io_texMem_req_ready),
    .io_texMem_req_valid           (io_texMem_req_valid),
    .io_texMem_req_bits_addr       (io_texMem_req_bits_addr),
    .io_texMem_resp_ready          (io_texMem_resp_ready),
    .io_texMem_resp_valid          (io_texMem_resp_valid),
    .io_texMem_resp_bits_data      (io_texMem_resp_bits_data),
    .io_texMem_resp_bits_write     (io_texMem_resp_bits_write),
    .io_texMem_resp_bits_addr      (io_texMem_resp_bits_addr),
    .io_done                       (_rp_io_done)
  );	// src/main/scala/opengpu/graphics/RenderCore.scala:87:26
  assign io_done = _cb_io_done & _rp_io_done;	// src/main/scala/opengpu/graphics/RenderCore.scala:35:7, :86:26, :87:26, :129:25
endmodule

