// Generated by CIRCT firtool-1.133.0
`ifndef layers_RenderHost_Verification_Assert	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
  `define layers_RenderHost_Verification_Assert
  `include "layers-RenderHost-Verification.sv"	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
  `include "layers-RenderCore-Verification-Assert.sv"	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
  `include "layers-FillEngine-Verification-Assert.sv"	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
  `include "layers-CopyEngine-Verification-Assert.sv"	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
  `include "layers-StridedCopyEngine-Verification-Assert.sv"	// src/main/scala/opengpu/graphics/RenderHost.scala:149:7
`endif // not def layers_RenderHost_Verification_Assert
