// Generated by CIRCT firtool-1.133.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TextureUnit_Verification_Assert();	// src/main/scala/opengpu/graphics/TextureUnit.scala:376:15
  `ifndef SYNTHESIS	// src/main/scala/opengpu/graphics/TextureUnit.scala:293:17
    wire _GEN = TextureUnit._io_sample_ready_T & TextureUnit._layer_probe_0;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/graphics/TextureUnit.scala:162:28, :290:28
    wire _GEN_0 =
      TextureUnit._layer_probe & TextureUnit.state_0 != 4'h1 & TextureUnit.state_0 != 4'h2
      & TextureUnit.state_0 != 4'h3 & TextureUnit.state_0 != 4'h4
      & TextureUnit._io_mem_resp_ready_T & TextureUnit._responseAccepted_T
      & ~TextureUnit.reset;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/graphics/TextureUnit.scala:97:7, :127:30, :162:28, :232:29, :288:17, :293:17, :314:15, :321:15, :332:13, :357:13, :373:30
    always @(posedge TextureUnit.clock) begin	// src/main/scala/opengpu/graphics/TextureUnit.scala:97:7, :293:17
      if (_GEN & ~TextureUnit.io_wrapMode & ~TextureUnit.reset
          & ~((TextureUnit.io_texWidth & TextureUnit.io_texWidth - 14'h1) == 14'h0
              & (TextureUnit.io_texHeight & TextureUnit.io_texHeight
                 - 14'h1) == 14'h0)) begin	// src/main/scala/opengpu/graphics/TextureUnit.scala:97:7, :100:14, :290:28, :292:{26,46}, :293:17, :294:{26,41,49,57}, :295:{29,45,53}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:293:17
          $error("Assertion failed: REPEAT wrapping requires power-of-two texture dimensions\n");	// src/main/scala/opengpu/graphics/TextureUnit.scala:293:17
        if (`STOP_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:293:17
          $fatal;	// src/main/scala/opengpu/graphics/TextureUnit.scala:293:17
      end
      if (_GEN & ~TextureUnit.reset
          & ~((|TextureUnit.io_texWidth) & (|TextureUnit.io_texHeight))) begin	// src/main/scala/opengpu/graphics/TextureUnit.scala:97:7, :100:14, :290:28, :293:17, :298:{15,28,36,52}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:298:15
          $error("Assertion failed: texture dimensions must be non-zero\n");	// src/main/scala/opengpu/graphics/TextureUnit.scala:298:15
        if (`STOP_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:298:15
          $fatal;	// src/main/scala/opengpu/graphics/TextureUnit.scala:298:15
      end
      if (_GEN_0 & ~TextureUnit._responseAccepted_T_1) begin	// src/main/scala/opengpu/graphics/TextureUnit.scala:246:54, :288:17, :373:30, :374:15
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:374:15
          $error("Assertion failed: texture reads must not receive a write acknowledgement\n");	// src/main/scala/opengpu/graphics/TextureUnit.scala:374:15
        if (`STOP_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:374:15
          $fatal;	// src/main/scala/opengpu/graphics/TextureUnit.scala:374:15
      end
      if (_GEN_0 & TextureUnit.responseMatchBits == 4'h0) begin	// src/main/scala/opengpu/graphics/TextureUnit.scala:245:51, :288:17, :373:30, :376:{15,34}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:376:15
          $error("Assertion failed: texture response must match an issued, pending tap address\n");	// src/main/scala/opengpu/graphics/TextureUnit.scala:376:15
        if (`STOP_COND_)	// src/main/scala/opengpu/graphics/TextureUnit.scala:376:15
          $fatal;	// src/main/scala/opengpu/graphics/TextureUnit.scala:376:15
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

