// Generated by CIRCT firtool-1.133.0
module FullInstructionDecoder(	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7
  input  [31:0] io_instruction,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output        io_decoded_illegalInstruction,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [2:0]  io_decoded_executionType,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output        io_decoded_scalar_legal,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [4:0]  io_decoded_scalar_rs1,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_rs2,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_rd,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [31:0] io_decoded_scalar_immediate,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [3:0]  io_decoded_scalar_aluOp,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [2:0]  io_decoded_scalar_branchOp,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output        io_decoded_scalar_useImmediate,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_usePc,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_useRs1,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_useRs2,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_writeRd,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_memoryRead,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_memoryWrite,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_jump,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_multiply,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_divide,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_atomic,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output [3:0]  io_decoded_scalar_atomicOp,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
  output        io_decoded_scalar_csr,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_system,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_fence,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_barrier,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_texSample,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_vectorBranch,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_join,	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
                io_decoded_scalar_cease	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:8:14
);

  wire       _vectorDecoder_io_decoded_valid;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:15:29
  wire       _fpuDecoder_io_decoded_valid;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:14:26
  wire       _scalarDecoder_io_decoded_legal;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  wire [2:0] _scalarDecoder_io_decoded_branchOp;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  wire       _scalarDecoder_io_decoded_memoryRead;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  wire       _scalarDecoder_io_decoded_memoryWrite;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  wire       _scalarDecoder_io_decoded_jump;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  wire       _scalarDecoder_io_decoded_system;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  RiscVDecoder scalarDecoder (	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
    .io_instruction          (io_instruction),
    .io_decoded_legal        (_scalarDecoder_io_decoded_legal),
    .io_decoded_rs1          (io_decoded_scalar_rs1),
    .io_decoded_rs2          (io_decoded_scalar_rs2),
    .io_decoded_rd           (io_decoded_scalar_rd),
    .io_decoded_immediate    (io_decoded_scalar_immediate),
    .io_decoded_aluOp        (io_decoded_scalar_aluOp),
    .io_decoded_branchOp     (_scalarDecoder_io_decoded_branchOp),
    .io_decoded_useImmediate (io_decoded_scalar_useImmediate),
    .io_decoded_usePc        (io_decoded_scalar_usePc),
    .io_decoded_useRs1       (io_decoded_scalar_useRs1),
    .io_decoded_useRs2       (io_decoded_scalar_useRs2),
    .io_decoded_writeRd      (io_decoded_scalar_writeRd),
    .io_decoded_memoryRead   (_scalarDecoder_io_decoded_memoryRead),
    .io_decoded_memoryWrite  (_scalarDecoder_io_decoded_memoryWrite),
    .io_decoded_jump         (_scalarDecoder_io_decoded_jump),
    .io_decoded_multiply     (io_decoded_scalar_multiply),
    .io_decoded_divide       (io_decoded_scalar_divide),
    .io_decoded_atomic       (io_decoded_scalar_atomic),
    .io_decoded_atomicOp     (io_decoded_scalar_atomicOp),
    .io_decoded_csr          (io_decoded_scalar_csr),
    .io_decoded_system       (_scalarDecoder_io_decoded_system),
    .io_decoded_fence        (io_decoded_scalar_fence),
    .io_decoded_barrier      (io_decoded_scalar_barrier),
    .io_decoded_texSample    (io_decoded_scalar_texSample),
    .io_decoded_vectorBranch (io_decoded_scalar_vectorBranch),
    .io_decoded_join         (io_decoded_scalar_join),
    .io_decoded_cease        (io_decoded_scalar_cease)
  );	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:13:29
  FpuDecoder fpuDecoder (	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:14:26
    .io_instruction   (io_instruction),
    .io_decoded_valid (_fpuDecoder_io_decoded_valid)
  );	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:14:26
  VectorDecoder vectorDecoder (	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:15:29
    .io_instruction   (io_instruction),
    .io_decoded_valid (_vectorDecoder_io_decoded_valid)
  );	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:15:29
  assign io_decoded_illegalInstruction =
    ~(_fpuDecoder_io_decoded_valid | _vectorDecoder_io_decoded_valid
      | _scalarDecoder_io_decoded_legal);	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29, :14:26, :15:29, :30:40, :43:65, :44:22, :51:59, :52:22, :59:36
  assign io_decoded_executionType =
    _fpuDecoder_io_decoded_valid
      ? 3'h4
      : _vectorDecoder_io_decoded_valid
          ? 3'h5
          : _scalarDecoder_io_decoded_legal
              ? ((|_scalarDecoder_io_decoded_branchOp) | _scalarDecoder_io_decoded_jump
                   ? 3'h2
                   : _scalarDecoder_io_decoded_memoryRead
                     | _scalarDecoder_io_decoded_memoryWrite
                       ? 3'h3
                       : _scalarDecoder_io_decoded_system ? 3'h6 : 3'h1)
              : 3'h0;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29, :14:26, :15:29, :22:28, :24:{56,74}, :26:58, :30:40, :32:{30,36}, :35:10, :38:12, :43:65, :45:30, :51:59, :53:30
  assign io_decoded_scalar_legal = _scalarDecoder_io_decoded_legal;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
  assign io_decoded_scalar_branchOp = _scalarDecoder_io_decoded_branchOp;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
  assign io_decoded_scalar_memoryRead = _scalarDecoder_io_decoded_memoryRead;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
  assign io_decoded_scalar_memoryWrite = _scalarDecoder_io_decoded_memoryWrite;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
  assign io_decoded_scalar_jump = _scalarDecoder_io_decoded_jump;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
  assign io_decoded_scalar_system = _scalarDecoder_io_decoded_system;	// src/main/scala/opengpu/core/frontend/decode/FullInstructionDecoder.scala:7:7, :13:29
endmodule

