// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BankedSharedMemory(	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
  input         clock,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
                reset,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
  output        io_in_ready,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input         io_in_valid,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input  [31:0] io_in_bits_addresses_0,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_addresses_1,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_addresses_2,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_addresses_3,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_writeData_0,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_writeData_1,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_writeData_2,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_in_bits_writeData_3,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input  [3:0]  io_in_bits_laneMask,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input  [1:0]  io_in_bits_elementSize,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input         io_in_bits_isStore,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_out_ready,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output        io_out_valid,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output [31:0] io_out_bits_readData_0,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_out_bits_readData_1,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_out_bits_readData_2,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_out_bits_readData_3,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output [3:0]  io_out_bits_faultMask,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output        io_atomicIn_ready,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input         io_atomicIn_valid,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input  [31:0] io_atomicIn_bits_address,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_atomicIn_bits_operand,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input  [3:0]  io_atomicIn_bits_operation,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  input         io_atomicOut_ready,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output        io_atomicOut_valid,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output [31:0] io_atomicOut_bits_oldValue,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
  output        io_atomicOut_bits_fault,	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
                io_idle	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:44:14
);

  wire [7:0]  _banks_3_ext_R0_data;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  wire [7:0]  _banks_2_ext_R0_data;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  wire [7:0]  _banks_1_ext_R0_data;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  wire [7:0]  _banks_0_ext_R0_data;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  reg  [31:0] transaction_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [31:0] transaction_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg         transaction_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
  reg  [15:0] pending;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:55:32
  reg         busy;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29
  reg  [31:0] result_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
  reg  [31:0] result_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
  reg  [31:0] result_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
  reg  [31:0] result_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
  reg  [3:0]  faultMask;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:58:34
  reg         outputValid;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:59:36
  reg  [2:0]  atomicState;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36
  reg  [31:0] atomicRequest_address;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
  reg  [31:0] atomicRequest_operand;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
  reg  [3:0]  atomicRequest_operation;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
  reg  [31:0] atomicOldValue;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:65:35
  reg  [31:0] atomicNewValue;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:66:35
  reg         atomicFault;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:67:36
  wire        _io_idle_T_3 = atomicState == 3'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :69:55
  wire        io_in_ready_0 = ~busy & ~outputValid & _io_idle_T_3 & ~io_atomicIn_valid;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29, :59:36, :69:{18,24,27,40,55,76}, :70:5
  wire        io_atomicIn_ready_0 = ~busy & ~outputValid & _io_idle_T_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29, :59:36, :69:{18,27,55}, :71:{30,46}
  wire        candidates_0 = pending[0] & transaction_addresses_0[1:0] == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_1 = pending[1] & transaction_addresses_0[1:0] + 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2 = pending[2] & transaction_addresses_0[1:0] - 2'h2 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3 = pending[3] & transaction_addresses_0[1:0] - 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_4 = pending[4] & transaction_addresses_1[1:0] == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_5 = pending[5] & transaction_addresses_1[1:0] + 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_6 = pending[6] & transaction_addresses_1[1:0] - 2'h2 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_7 = pending[7] & transaction_addresses_1[1:0] - 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_8 = pending[8] & transaction_addresses_2[1:0] == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_9 = pending[9] & transaction_addresses_2[1:0] + 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_10 = pending[10] & transaction_addresses_2[1:0] - 2'h2 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_11 = pending[11] & transaction_addresses_2[1:0] - 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_12 = pending[12] & transaction_addresses_3[1:0] == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_13 = pending[13] & transaction_addresses_3[1:0] + 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_14 = pending[14] & transaction_addresses_3[1:0] - 2'h2 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire [15:0] candidateBits =
    {pending[15] & transaction_addresses_3[1:0] - 2'h1 == 2'h0,
     candidates_14,
     candidates_13,
     candidates_12,
     candidates_11,
     candidates_10,
     candidates_9,
     candidates_8,
     candidates_7,
     candidates_6,
     candidates_5,
     candidates_4,
     candidates_3,
     candidates_2,
     candidates_1,
     candidates_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34, :122:36
  wire [3:0]  selected =
    candidates_0
      ? 4'h0
      : candidates_1
          ? 4'h1
          : candidates_2
              ? 4'h2
              : candidates_3
                  ? 4'h3
                  : candidates_4
                      ? 4'h4
                      : candidates_5
                          ? 4'h5
                          : candidates_6
                              ? 4'h6
                              : candidates_7
                                  ? 4'h7
                                  : candidates_8
                                      ? 4'h8
                                      : candidates_9
                                          ? 4'h9
                                          : candidates_10
                                              ? 4'hA
                                              : candidates_11
                                                  ? 4'hB
                                                  : candidates_12
                                                      ? 4'hC
                                                      : candidates_13
                                                          ? 4'hD
                                                          : {3'h7, ~candidates_14};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23, :85:18, :119:51
  reg  [31:0] casez_tmp;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
    casez (selected[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
      2'b00:
        casez_tmp = transaction_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b01:
        casez_tmp = transaction_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b10:
        casez_tmp = transaction_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      default:
        casez_tmp = transaction_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
  end // always_comb
  wire [7:0]  _selectedOffset_T_2 = casez_tmp[7:0] + {6'h0, selected[1:0]};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :128:{43,71}
  wire        issueVectorRead = (|candidateBits) & ~transaction_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :132:{40,43}
  wire        atomicByteMatch_0 = atomicRequest_address[1:0] == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :133:46, :137:{32,51}
  wire        atomicByteMatch_1 = atomicRequest_address[1:0] + 2'h1 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire        atomicByteMatch_2 = atomicRequest_address[1:0] - 2'h2 == 2'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire [3:0]  atomicByteBits =
    {atomicRequest_address[1:0] - 2'h1 == 2'h0,
     atomicByteMatch_2,
     atomicByteMatch_1,
     atomicByteMatch_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}, :139:42
  wire [1:0]  atomicByte =
    atomicByteMatch_0 ? 2'h0 : atomicByteMatch_1 ? 2'h1 : {1'h1, ~atomicByteMatch_2};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:137:51
  wire [7:0]  _atomicBankAddress_T = atomicRequest_address[7:0] + {6'h0, atomicByte};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :142:43
  wire        _issueAtomicRead_T_3 = atomicState == 3'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :97:23, :143:39
  wire        issueAtomicRead = _issueAtomicRead_T_3 & (|atomicByteBits);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :143:{39,60}
  reg         responseValid;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
  reg  [1:0]  responseLane;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:148:33
  reg  [1:0]  responseByte;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33
  reg         atomicResponseValid;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
  reg  [1:0]  atomicResponseByte;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
  wire        _issueAtomicWrite_T_3 = atomicState == 3'h3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :163:19, :229:17
  wire        issueAtomicWrite = _issueAtomicWrite_T_3 & (|atomicByteBits);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :163:{19,41}
  reg  [31:0] casez_tmp_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
    casez (selected[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
      2'b00:
        casez_tmp_0 = transaction_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b01:
        casez_tmp_0 = transaction_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b10:
        casez_tmp_0 = transaction_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      default:
        casez_tmp_0 = transaction_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
  end // always_comb
  wire [31:0] _vectorWriteData_T_1 = casez_tmp_0 >> {27'h0, selected[1:0], 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :166:44
  wire [31:0] _atomicWriteData_T_1 = atomicNewValue >> {27'h0, atomicByte, 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:66:35, :166:44, :168:23
  wire        candidates_1_0 = pending[0] & transaction_addresses_0[1:0] == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_1_1 = pending[1] & transaction_addresses_0[1:0] + 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_2 = pending[2] & transaction_addresses_0[1:0] - 2'h2 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_3 = pending[3] & transaction_addresses_0[1:0] - 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_4 = pending[4] & transaction_addresses_1[1:0] == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_1_5 = pending[5] & transaction_addresses_1[1:0] + 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_6 = pending[6] & transaction_addresses_1[1:0] - 2'h2 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_7 = pending[7] & transaction_addresses_1[1:0] - 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_8 = pending[8] & transaction_addresses_2[1:0] == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_1_9 = pending[9] & transaction_addresses_2[1:0] + 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_10 = pending[10] & transaction_addresses_2[1:0] - 2'h2 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_11 = pending[11] & transaction_addresses_2[1:0] - 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_12 = pending[12] & transaction_addresses_3[1:0] == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_1_13 = pending[13] & transaction_addresses_3[1:0] + 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_1_14 = pending[14] & transaction_addresses_3[1:0] - 2'h2 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire [15:0] candidateBits_1 =
    {pending[15] & transaction_addresses_3[1:0] - 2'h1 == 2'h1,
     candidates_1_14,
     candidates_1_13,
     candidates_1_12,
     candidates_1_11,
     candidates_1_10,
     candidates_1_9,
     candidates_1_8,
     candidates_1_7,
     candidates_1_6,
     candidates_1_5,
     candidates_1_4,
     candidates_1_3,
     candidates_1_2,
     candidates_1_1,
     candidates_1_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34, :122:36
  wire [3:0]  selected_1 =
    candidates_1_0
      ? 4'h0
      : candidates_1_1
          ? 4'h1
          : candidates_1_2
              ? 4'h2
              : candidates_1_3
                  ? 4'h3
                  : candidates_1_4
                      ? 4'h4
                      : candidates_1_5
                          ? 4'h5
                          : candidates_1_6
                              ? 4'h6
                              : candidates_1_7
                                  ? 4'h7
                                  : candidates_1_8
                                      ? 4'h8
                                      : candidates_1_9
                                          ? 4'h9
                                          : candidates_1_10
                                              ? 4'hA
                                              : candidates_1_11
                                                  ? 4'hB
                                                  : candidates_1_12
                                                      ? 4'hC
                                                      : candidates_1_13
                                                          ? 4'hD
                                                          : {3'h7, ~candidates_1_14};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23, :85:18, :119:51
  reg  [31:0] casez_tmp_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
    casez (selected_1[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
      2'b00:
        casez_tmp_1 = transaction_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b01:
        casez_tmp_1 = transaction_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b10:
        casez_tmp_1 = transaction_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      default:
        casez_tmp_1 = transaction_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
  end // always_comb
  wire [7:0]  _selectedOffset_T_5 = casez_tmp_1[7:0] + {6'h0, selected_1[1:0]};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :128:{43,71}
  wire        readIssued_1 = (|candidateBits_1) & ~transaction_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :132:{40,43}
  wire        atomicByteMatch_1_0 = atomicRequest_address[1:0] == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :133:46, :137:{32,51}
  wire        atomicByteMatch_1_1 = atomicRequest_address[1:0] + 2'h1 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire        atomicByteMatch_1_2 = atomicRequest_address[1:0] - 2'h2 == 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire [3:0]  atomicByteBits_1 =
    {atomicRequest_address[1:0] - 2'h1 == 2'h1,
     atomicByteMatch_1_2,
     atomicByteMatch_1_1,
     atomicByteMatch_1_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}, :139:42
  wire [1:0]  atomicByte_1 =
    atomicByteMatch_1_0
      ? 2'h0
      : atomicByteMatch_1_1 ? 2'h1 : {1'h1, ~atomicByteMatch_1_2};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:137:51
  wire [7:0]  _atomicBankAddress_T_2 = atomicRequest_address[7:0] + {6'h0, atomicByte_1};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :142:43
  wire        issueAtomicRead_1 = _issueAtomicRead_T_3 & (|atomicByteBits_1);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :143:{39,60}
  reg         responseValid_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
  reg  [1:0]  responseLane_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:148:33
  reg  [1:0]  responseByte_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33
  reg         atomicResponseValid_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
  reg  [1:0]  atomicResponseByte_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
  wire        issueAtomicWrite_1 = _issueAtomicWrite_T_3 & (|atomicByteBits_1);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :163:{19,41}
  reg  [31:0] casez_tmp_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
    casez (selected_1[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
      2'b00:
        casez_tmp_2 = transaction_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b01:
        casez_tmp_2 = transaction_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b10:
        casez_tmp_2 = transaction_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      default:
        casez_tmp_2 = transaction_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
  end // always_comb
  wire [31:0] _vectorWriteData_T_3 = casez_tmp_2 >> {27'h0, selected_1[1:0], 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :166:44
  wire [31:0] _atomicWriteData_T_3 = atomicNewValue >> {27'h0, atomicByte_1, 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:66:35, :166:44, :168:23
  wire        candidates_2_0 = pending[0] & transaction_addresses_0[1:0] == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_2_1 = pending[1] & transaction_addresses_0[1:0] + 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_2 = pending[2] & transaction_addresses_0[1:0] - 2'h2 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_3 = pending[3] & transaction_addresses_0[1:0] - 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_4 = pending[4] & transaction_addresses_1[1:0] == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_2_5 = pending[5] & transaction_addresses_1[1:0] + 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_6 = pending[6] & transaction_addresses_1[1:0] - 2'h2 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_7 = pending[7] & transaction_addresses_1[1:0] - 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_8 = pending[8] & transaction_addresses_2[1:0] == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_2_9 = pending[9] & transaction_addresses_2[1:0] + 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_10 = pending[10] & transaction_addresses_2[1:0] - 2'h2 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_11 = pending[11] & transaction_addresses_2[1:0] - 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_12 = pending[12] & transaction_addresses_3[1:0] == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_2_13 = pending[13] & transaction_addresses_3[1:0] + 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_2_14 = pending[14] & transaction_addresses_3[1:0] - 2'h2 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire [15:0] candidateBits_2 =
    {pending[15] & transaction_addresses_3[1:0] - 2'h1 == 2'h2,
     candidates_2_14,
     candidates_2_13,
     candidates_2_12,
     candidates_2_11,
     candidates_2_10,
     candidates_2_9,
     candidates_2_8,
     candidates_2_7,
     candidates_2_6,
     candidates_2_5,
     candidates_2_4,
     candidates_2_3,
     candidates_2_2,
     candidates_2_1,
     candidates_2_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34, :122:36
  wire [3:0]  selected_2 =
    candidates_2_0
      ? 4'h0
      : candidates_2_1
          ? 4'h1
          : candidates_2_2
              ? 4'h2
              : candidates_2_3
                  ? 4'h3
                  : candidates_2_4
                      ? 4'h4
                      : candidates_2_5
                          ? 4'h5
                          : candidates_2_6
                              ? 4'h6
                              : candidates_2_7
                                  ? 4'h7
                                  : candidates_2_8
                                      ? 4'h8
                                      : candidates_2_9
                                          ? 4'h9
                                          : candidates_2_10
                                              ? 4'hA
                                              : candidates_2_11
                                                  ? 4'hB
                                                  : candidates_2_12
                                                      ? 4'hC
                                                      : candidates_2_13
                                                          ? 4'hD
                                                          : {3'h7, ~candidates_2_14};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23, :85:18, :119:51
  reg  [31:0] casez_tmp_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
    casez (selected_2[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
      2'b00:
        casez_tmp_3 = transaction_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b01:
        casez_tmp_3 = transaction_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b10:
        casez_tmp_3 = transaction_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      default:
        casez_tmp_3 = transaction_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
  end // always_comb
  wire [7:0]  _selectedOffset_T_8 = casez_tmp_3[7:0] + {6'h0, selected_2[1:0]};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :128:{43,71}
  wire        readIssued_2 = (|candidateBits_2) & ~transaction_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :132:{40,43}
  wire        atomicByteMatch_2_0 = atomicRequest_address[1:0] == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :133:46, :137:{32,51}
  wire        atomicByteMatch_2_1 = atomicRequest_address[1:0] + 2'h1 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire        atomicByteMatch_2_2 = atomicRequest_address[1:0] - 2'h2 == 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}
  wire [3:0]  atomicByteBits_2 =
    {atomicRequest_address[1:0] - 2'h1 == 2'h2,
     atomicByteMatch_2_2,
     atomicByteMatch_2_1,
     atomicByteMatch_2_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:{23,51}, :139:42
  wire [1:0]  atomicByte_2 =
    atomicByteMatch_2_0
      ? 2'h0
      : atomicByteMatch_2_1 ? 2'h1 : {1'h1, ~atomicByteMatch_2_2};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:137:51
  wire [7:0]  _atomicBankAddress_T_4 = atomicRequest_address[7:0] + {6'h0, atomicByte_2};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :142:43
  wire        issueAtomicRead_2 = _issueAtomicRead_T_3 & (|atomicByteBits_2);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :143:{39,60}
  reg         responseValid_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
  reg  [1:0]  responseLane_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:148:33
  reg  [1:0]  responseByte_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33
  reg         atomicResponseValid_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
  reg  [1:0]  atomicResponseByte_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
  wire        issueAtomicWrite_2 = _issueAtomicWrite_T_3 & (|atomicByteBits_2);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :163:{19,41}
  reg  [31:0] casez_tmp_4;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
    casez (selected_2[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
      2'b00:
        casez_tmp_4 = transaction_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b01:
        casez_tmp_4 = transaction_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b10:
        casez_tmp_4 = transaction_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      default:
        casez_tmp_4 = transaction_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
  end // always_comb
  wire [31:0] _vectorWriteData_T_5 = casez_tmp_4 >> {27'h0, selected_2[1:0], 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :166:44
  wire [31:0] _atomicWriteData_T_5 = atomicNewValue >> {27'h0, atomicByte_2, 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:66:35, :166:44, :168:23
  wire        candidates_3_0 = pending[0] & (&(transaction_addresses_0[1:0]));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_3_1 = pending[1] & (&(transaction_addresses_0[1:0] + 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_2 = pending[2] & (&(transaction_addresses_0[1:0] - 2'h2));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_3 = pending[3] & (&(transaction_addresses_0[1:0] - 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_4 = pending[4] & (&(transaction_addresses_1[1:0]));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_3_5 = pending[5] & (&(transaction_addresses_1[1:0] + 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_6 = pending[6] & (&(transaction_addresses_1[1:0] - 2'h2));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_7 = pending[7] & (&(transaction_addresses_1[1:0] - 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_8 = pending[8] & (&(transaction_addresses_2[1:0]));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_3_9 = pending[9] & (&(transaction_addresses_2[1:0] + 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_10 = pending[10] & (&(transaction_addresses_2[1:0] - 2'h2));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_11 = pending[11] & (&(transaction_addresses_2[1:0] - 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_12 = pending[12] & (&(transaction_addresses_3[1:0]));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :119:{39,51}, :120:34
  wire        candidates_3_13 = pending[13] & (&(transaction_addresses_3[1:0] + 2'h1));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire        candidates_3_14 = pending[14] & (&(transaction_addresses_3[1:0] - 2'h2));	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34
  wire [15:0] candidateBits_3 =
    {pending[15] & (&(transaction_addresses_3[1:0] - 2'h1)),
     candidates_3_14,
     candidates_3_13,
     candidates_3_12,
     candidates_3_11,
     candidates_3_10,
     candidates_3_9,
     candidates_3_8,
     candidates_3_7,
     candidates_3_6,
     candidates_3_5,
     candidates_3_4,
     candidates_3_3,
     candidates_3_2,
     candidates_3_1,
     candidates_3_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :55:32, :118:76, :119:{39,51}, :120:34, :122:36
  wire [3:0]  selected_3 =
    candidates_3_0
      ? 4'h0
      : candidates_3_1
          ? 4'h1
          : candidates_3_2
              ? 4'h2
              : candidates_3_3
                  ? 4'h3
                  : candidates_3_4
                      ? 4'h4
                      : candidates_3_5
                          ? 4'h5
                          : candidates_3_6
                              ? 4'h6
                              : candidates_3_7
                                  ? 4'h7
                                  : candidates_3_8
                                      ? 4'h8
                                      : candidates_3_9
                                          ? 4'h9
                                          : candidates_3_10
                                              ? 4'hA
                                              : candidates_3_11
                                                  ? 4'hB
                                                  : candidates_3_12
                                                      ? 4'hC
                                                      : candidates_3_13
                                                          ? 4'hD
                                                          : {3'h7, ~candidates_3_14};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23, :85:18, :119:51
  reg  [31:0] casez_tmp_5;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:43
    casez (selected_3[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
      2'b00:
        casez_tmp_5 = transaction_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b01:
        casez_tmp_5 = transaction_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      2'b10:
        casez_tmp_5 = transaction_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
      default:
        casez_tmp_5 = transaction_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :128:43
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :128:43
  end // always_comb
  wire [7:0]  _selectedOffset_T_11 = casez_tmp_5[7:0] + {6'h0, selected_3[1:0]};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :128:{43,71}
  wire        readIssued_3 = (|candidateBits_3) & ~transaction_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :132:{40,43}
  wire [1:0]  _atomicByteMatch_1_T_12 = atomicRequest_address[1:0] + 2'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:23
  wire [1:0]  _atomicByteMatch_2_T_12 = atomicRequest_address[1:0] - 2'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :137:23
  wire [3:0]  atomicByteBits_3 =
    {&(atomicRequest_address[1:0] - 2'h1),
     &_atomicByteMatch_2_T_12,
     &_atomicByteMatch_1_T_12,
     &(atomicRequest_address[1:0])};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :133:46, :137:{23,32,51}, :139:42
  wire [1:0]  atomicByte_3 =
    (&(atomicRequest_address[1:0]))
      ? 2'h0
      : (&_atomicByteMatch_1_T_12) ? 2'h1 : {1'h1, ~(&_atomicByteMatch_2_T_12)};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :133:46, :137:{23,32,51}
  wire [7:0]  _atomicBankAddress_T_6 = atomicRequest_address[7:0] + {6'h0, atomicByte_3};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :142:43
  wire        issueAtomicRead_3 = _issueAtomicRead_T_3 & (|atomicByteBits_3);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :143:{39,60}
  reg         responseValid_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
  reg  [1:0]  responseLane_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:148:33
  reg  [1:0]  responseByte_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33
  reg         atomicResponseValid_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
  reg  [1:0]  atomicResponseByte_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
  wire        issueAtomicWrite_3 = _issueAtomicWrite_T_3 & (|atomicByteBits_3);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:139:42, :140:40, :163:{19,41}
  reg  [31:0] casez_tmp_6;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
  always_comb begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:166:44
    casez (selected_3[3:2])	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
      2'b00:
        casez_tmp_6 = transaction_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b01:
        casez_tmp_6 = transaction_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      2'b10:
        casez_tmp_6 = transaction_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
      default:
        casez_tmp_6 = transaction_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :166:44
    endcase	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :166:44
  end // always_comb
  wire [31:0] _vectorWriteData_T_7 = casez_tmp_6 >> {27'h0, selected_3[1:0], 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :166:44
  wire [31:0] _atomicWriteData_T_7 = atomicNewValue >> {27'h0, atomicByte_3, 3'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:66:35, :166:44, :168:23
  wire        io_atomicOut_valid_0 = atomicState == 3'h4;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :95:32, :234:37
  wire [3:0]  bytes = 4'h1 << io_in_bits_elementSize;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23
  wire [31:0] _GEN = {28'h0, bytes};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:79:23, :82:17
  wire        faults_0 =
    io_in_bits_laneMask[0] & io_in_bits_addresses_0 + _GEN - 32'h10000000 > 32'h100;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:80:47, :81:{42,49}, :82:{17,25}
  wire        faults_1 =
    io_in_bits_laneMask[1] & io_in_bits_addresses_1 + _GEN - 32'h10000000 > 32'h100;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:80:47, :81:{42,49}, :82:{17,25}
  wire        faults_2 =
    io_in_bits_laneMask[2] & io_in_bits_addresses_2 + _GEN - 32'h10000000 > 32'h100;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:80:47, :81:{42,49}, :82:{17,25}
  wire        faults_3 =
    io_in_bits_laneMask[3] & io_in_bits_addresses_3 + _GEN - 32'h10000000 > 32'h100;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:80:47, :81:{42,49}, :82:{17,25}
  wire        _atomicState_T_2 = io_atomicIn_bits_address < 32'h10000000;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:94:32
  wire [31:0] _atomicState_T_4 = io_atomicIn_bits_address + 32'h4;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:95:32
  wire [15:0] remaining =
    pending
    & ~(((|candidateBits) ? 16'h1 << selected : 16'h0)
        | ((|candidateBits_1) ? 16'h1 << selected_1 : 16'h0)
        | ((|candidateBits_2) ? 16'h1 << selected_2 : 16'h0)
        | ((|candidateBits_3) ? 16'h1 << selected_3 : 16'h0));	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/chisel3/util/OneHot.scala:65:12, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:55:32, :122:36, :123:38, :130:32, :176:50, :185:{29,31}
  wire        _GEN_0 =
    busy & remaining == 16'h0
    & {readIssued_3, readIssued_2, readIssued_1, issueVectorRead} == 4'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29, :72:20, :85:18, :132:40, :178:14, :185:29, :190:{21,25,40,47,52}, :191:12
  wire        _GEN_1 = io_atomicOut_ready & io_atomicOut_valid_0;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:234:37
  wire        _GEN_2 = io_in_ready_0 & io_in_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:69:{24,40,76}
  wire        _GEN_3 = io_atomicIn_ready_0 & io_atomicIn_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:71:{30,46}
  wire [38:0] _GEN_4 = {31'h0, _banks_0_ext_R0_data};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16, :118:76, :155:34
  wire [38:0] _GEN_5 = {31'h0, _banks_1_ext_R0_data};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16, :118:76, :155:34
  wire [38:0] _GEN_6 = {31'h0, _banks_2_ext_R0_data};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16, :118:76, :155:34
  wire [38:0] _GEN_7 = {31'h0, _banks_3_ext_R0_data};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16, :118:76, :155:34
  wire        _GEN_8 = atomicState == 3'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :203:17, :205:20
  wire [38:0] _atomicBytes_3_T_1 = _GEN_7 << {34'h0, atomicResponseByte_3, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39, :155:34, :158:18
  wire [38:0] _atomicBytes_2_T_1 = _GEN_6 << {34'h0, atomicResponseByte_2, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39, :155:34, :158:18
  wire [38:0] _atomicBytes_1_T_1 = _GEN_5 << {34'h0, atomicResponseByte_1, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39, :155:34, :158:18
  wire [38:0] _atomicBytes_0_T_1 = _GEN_4 << {34'h0, atomicResponseByte, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39, :155:34, :158:18
  wire [31:0] atomicReadWord =
    (atomicResponseValid ? _atomicBytes_0_T_1[31:0] : 32'h0)
    | (atomicResponseValid_1 ? _atomicBytes_1_T_1[31:0] : 32'h0)
    | (atomicResponseValid_2 ? _atomicBytes_2_T_1[31:0] : 32'h0)
    | (atomicResponseValid_3 ? _atomicBytes_3_T_1[31:0] : 32'h0);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38, :156:29, :158:18, :201:53
  wire [38:0] _readData_0_T_1 = _GEN_4 << {34'h0, responseByte, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33, :155:34
  wire [38:0] _readData_1_T_1 = _GEN_5 << {34'h0, responseByte_1, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33, :155:34
  wire [38:0] _readData_2_T_1 = _GEN_6 << {34'h0, responseByte_2, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33, :155:34
  wire [38:0] _readData_3_T_1 = _GEN_7 << {34'h0, responseByte_3, 3'h0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:149:33, :155:34
  always @(posedge clock) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
    if (_GEN_2) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      transaction_addresses_0 <= io_in_bits_addresses_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_addresses_1 <= io_in_bits_addresses_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_addresses_2 <= io_in_bits_addresses_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_addresses_3 <= io_in_bits_addresses_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_writeData_0 <= io_in_bits_writeData_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_writeData_1 <= io_in_bits_writeData_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_writeData_2 <= io_in_bits_writeData_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_writeData_3 <= io_in_bits_writeData_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
      transaction_isStore <= io_in_bits_isStore;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32
    end
    if (_GEN_3) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      atomicRequest_address <= io_atomicIn_bits_address;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
      atomicRequest_operand <= io_atomicIn_bits_operand;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
      atomicRequest_operation <= io_atomicIn_bits_operation;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34
    end
    if (_GEN_8) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:205:20
      atomicOldValue <= atomicReadWord;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:65:35, :201:53
      atomicNewValue <=
        atomicRequest_operation == 4'h8
          ? (atomicReadWord > atomicRequest_operand
               ? atomicReadWord
               : atomicRequest_operand)
          : atomicRequest_operation == 4'h7
              ? (atomicReadWord < atomicRequest_operand
                   ? atomicReadWord
                   : atomicRequest_operand)
              : atomicRequest_operation == 4'h6
                  ? ($signed(atomicReadWord) > $signed(atomicRequest_operand)
                       ? atomicReadWord
                       : atomicRequest_operand)
                  : atomicRequest_operation == 4'h5
                      ? ($signed(atomicReadWord) < $signed(atomicRequest_operand)
                           ? atomicReadWord
                           : atomicRequest_operand)
                      : atomicRequest_operation == 4'h4
                          ? atomicReadWord & atomicRequest_operand
                          : atomicRequest_operation == 4'h3
                              ? atomicReadWord | atomicRequest_operand
                              : atomicRequest_operation == 4'h2
                                  ? atomicReadWord ^ atomicRequest_operand
                                  : atomicRequest_operation == 4'h1
                                      ? atomicReadWord + atomicRequest_operand
                                      : atomicRequest_operand;	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:64:34, :66:35, :79:23, :85:18, :201:53, :210:6, :212:45, :213:45, :214:44, :215:45, :216:32, :217:31, :219:32, :220:31, :222:33, :223:24, :225:33, :226:24
    end
    if (issueVectorRead) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40
      responseLane <= selected[3:2];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :148:33
      responseByte <= selected[1:0];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :149:33
    end
    if (issueAtomicRead)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60
      atomicResponseByte <= atomicByte;	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
    if (readIssued_1) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40
      responseLane_1 <= selected_1[3:2];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :148:33
      responseByte_1 <= selected_1[1:0];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :149:33
    end
    if (issueAtomicRead_1)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60
      atomicResponseByte_1 <= atomicByte_1;	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
    if (readIssued_2) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40
      responseLane_2 <= selected_2[3:2];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :148:33
      responseByte_2 <= selected_2[1:0];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :149:33
    end
    if (issueAtomicRead_2)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60
      atomicResponseByte_2 <= atomicByte_2;	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
    if (readIssued_3) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40
      responseLane_3 <= selected_3[3:2];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:125:33, :148:33
      responseByte_3 <= selected_3[1:0];	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:126:32, :149:33
    end
    if (issueAtomicRead_3)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60
      atomicResponseByte_3 <= atomicByte_3;	// src/main/scala/chisel3/util/Mux.scala:58:84, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:151:39
    if (reset) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      pending <= 16'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:55:32
      busy <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29
      result_0 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
      result_1 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
      result_2 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
      result_3 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
      faultMask <= 4'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:58:34, :85:18
      outputValid <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:59:36
      atomicState <= 3'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36
      atomicFault <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:67:36
      responseValid <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
      atomicResponseValid <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
      responseValid_1 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
      atomicResponseValid_1 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
      responseValid_2 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
      atomicResponseValid_2 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
      responseValid_3 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:147:32
      atomicResponseValid_3 <= 1'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:150:38
    end
    else begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      if (busy)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29
        pending <= remaining;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:55:32, :185:29
      else if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        pending <=
          {io_in_bits_laneMask[3] & (|(bytes[3:2])) & ~faults_3,
           io_in_bits_laneMask[3] & bytes > 4'h2 & ~faults_3,
           io_in_bits_laneMask[3] & (|(bytes[3:1])) & ~faults_3,
           io_in_bits_laneMask[3] & (|bytes) & ~faults_3,
           io_in_bits_laneMask[2] & (|(bytes[3:2])) & ~faults_2,
           io_in_bits_laneMask[2] & bytes > 4'h2 & ~faults_2,
           io_in_bits_laneMask[2] & (|(bytes[3:1])) & ~faults_2,
           io_in_bits_laneMask[2] & (|bytes) & ~faults_2,
           io_in_bits_laneMask[1] & (|(bytes[3:2])) & ~faults_1,
           io_in_bits_laneMask[1] & bytes > 4'h2 & ~faults_1,
           io_in_bits_laneMask[1] & (|(bytes[3:1])) & ~faults_1,
           io_in_bits_laneMask[1] & (|bytes) & ~faults_1,
           io_in_bits_laneMask[0] & (|(bytes[3:2])) & ~faults_0,
           io_in_bits_laneMask[0] & bytes > 4'h2 & ~faults_0,
           io_in_bits_laneMask[0] & (|(bytes[3:1])) & ~faults_0,
           io_in_bits_laneMask[0] & (|bytes) & ~faults_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:55:32, :79:23, :81:{42,49}, :84:67, :85:{18,26,29}, :88:28
      busy <= ~_GEN_0 & (_GEN_2 | busy);	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29, :72:20, :74:10, :178:14, :190:{25,52}, :191:12
      if (busy) begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:56:29
        result_0 <=
          result_0
          | (responseValid & responseLane == 2'h0 ? _readData_0_T_1[31:0] : 32'h0)
          | (responseValid_1 & responseLane_1 == 2'h0 ? _readData_1_T_1[31:0] : 32'h0)
          | (responseValid_2 & responseLane_2 == 2'h0 ? _readData_2_T_1[31:0] : 32'h0)
          | (responseValid_3 & responseLane_3 == 2'h0 ? _readData_3_T_1[31:0] : 32'h0);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31, :147:32, :148:33, :155:{20,34}, :181:{12,29,47}, :182:18, :183:36
        result_1 <=
          result_1
          | (responseValid & responseLane == 2'h1 ? _readData_0_T_1[31:0] : 32'h0)
          | (responseValid_1 & responseLane_1 == 2'h1 ? _readData_1_T_1[31:0] : 32'h0)
          | (responseValid_2 & responseLane_2 == 2'h1 ? _readData_2_T_1[31:0] : 32'h0)
          | (responseValid_3 & responseLane_3 == 2'h1 ? _readData_3_T_1[31:0] : 32'h0);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31, :147:32, :148:33, :155:{20,34}, :181:{12,29,47}, :182:18, :183:36
        result_2 <=
          result_2
          | (responseValid & responseLane == 2'h2 ? _readData_0_T_1[31:0] : 32'h0)
          | (responseValid_1 & responseLane_1 == 2'h2 ? _readData_1_T_1[31:0] : 32'h0)
          | (responseValid_2 & responseLane_2 == 2'h2 ? _readData_2_T_1[31:0] : 32'h0)
          | (responseValid_3 & responseLane_3 == 2'h2 ? _readData_3_T_1[31:0] : 32'h0);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31, :147:32, :148:33, :155:{20,34}, :181:{12,29,47}, :182:18, :183:36
        result_3 <=
          result_3 | (responseValid & (&responseLane) ? _readData_0_T_1[31:0] : 32'h0)
          | (responseValid_1 & (&responseLane_1) ? _readData_1_T_1[31:0] : 32'h0)
          | (responseValid_2 & (&responseLane_2) ? _readData_2_T_1[31:0] : 32'h0)
          | (responseValid_3 & (&responseLane_3) ? _readData_3_T_1[31:0] : 32'h0);	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31, :147:32, :148:33, :155:{20,34}, :181:{12,29,47}, :182:18, :183:36
      end
      else if (_GEN_2) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        result_0 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
        result_1 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
        result_2 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
        result_3 <= 32'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:57:31
      end
      if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        faultMask <= {faults_3, faults_2, faults_1, faults_0};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:58:34, :81:49, :89:25
      outputValid <= ~(io_out_ready & outputValid) & (_GEN_0 | outputValid);	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:59:36, :72:20, :178:14, :190:{25,52}, :191:12, :192:19, :200:{21,35}
      if (_GEN_1)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        atomicState <= 3'h0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36
      else if (_issueAtomicWrite_T_3)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:163:19
        atomicState <= 3'h4;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :95:32
      else if (_GEN_8)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:205:20
        atomicState <= 3'h3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :229:17
      else if (_issueAtomicRead_T_3)	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:39
        atomicState <= 3'h2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :203:17
      else if (_GEN_3)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        atomicState <=
          (|(io_atomicIn_bits_address[1:0])) | _atomicState_T_2
          | _atomicState_T_4 > 32'h10000100
            ? 3'h4
            : 3'h1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:63:36, :93:44, :94:32, :95:{32,38}, :97:23, :98:{38,42}, :99:62, :100:40
      atomicFault <=
        ~_GEN_1
        & (_GEN_3
             ? (|(io_atomicIn_bits_address[1:0])) | _atomicState_T_2
               | _atomicState_T_4 > 32'h10000100
             : atomicFault);	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:67:36, :91:26, :93:{17,44,51,55}, :94:{32,60}, :95:{32,38}, :238:27, :240:17
      responseValid <= issueVectorRead;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :147:32
      atomicResponseValid <= issueAtomicRead;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60, :150:38
      responseValid_1 <= readIssued_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :147:32
      atomicResponseValid_1 <= issueAtomicRead_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60, :150:38
      responseValid_2 <= readIssued_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :147:32
      atomicResponseValid_2 <= issueAtomicRead_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60, :150:38
      responseValid_3 <= readIssued_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :147:32
      atomicResponseValid_3 <= issueAtomicRead_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:143:60, :150:38
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
    initial begin	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
        end	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
        transaction_addresses_0 = {_RANDOM[5'h0][31:2], _RANDOM[5'h1][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_addresses_1 = {_RANDOM[5'h1][31:2], _RANDOM[5'h2][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_addresses_2 = {_RANDOM[5'h2][31:2], _RANDOM[5'h3][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_addresses_3 = {_RANDOM[5'h3][31:2], _RANDOM[5'h4][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_writeData_0 = {_RANDOM[5'h4][31:2], _RANDOM[5'h5][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_writeData_1 = {_RANDOM[5'h5][31:2], _RANDOM[5'h6][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_writeData_2 = {_RANDOM[5'h6][31:2], _RANDOM[5'h7][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_writeData_3 = {_RANDOM[5'h7][31:2], _RANDOM[5'h8][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        transaction_isStore = _RANDOM[5'h8][8];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32
        pending = _RANDOM[5'h8][24:9];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32, :55:32
        busy = _RANDOM[5'h8][25];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32, :56:29
        result_0 = {_RANDOM[5'h8][31:26], _RANDOM[5'h9][25:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :54:32, :57:31
        result_1 = {_RANDOM[5'h9][31:26], _RANDOM[5'hA][25:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
        result_2 = {_RANDOM[5'hA][31:26], _RANDOM[5'hB][25:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
        result_3 = {_RANDOM[5'hB][31:26], _RANDOM[5'hC][25:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
        faultMask = _RANDOM[5'hC][29:26];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31, :58:34
        outputValid = _RANDOM[5'hC][30];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31, :59:36
        atomicState = {_RANDOM[5'hC][31], _RANDOM[5'hD][1:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31, :63:36
        atomicRequest_address = {_RANDOM[5'hD][31:4], _RANDOM[5'hE][3:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :63:36, :64:34
        atomicRequest_operand = {_RANDOM[5'hE][31:4], _RANDOM[5'hF][3:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :64:34
        atomicRequest_operation = _RANDOM[5'hF][7:4];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :64:34
        atomicOldValue = {_RANDOM[5'hF][31:8], _RANDOM[5'h10][7:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :64:34, :65:35
        atomicNewValue = {_RANDOM[5'h10][31:8], _RANDOM[5'h11][7:0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :65:35, :66:35
        atomicFault = _RANDOM[5'h11][8];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :67:36
        responseValid = _RANDOM[5'h11][9];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :147:32
        responseLane = _RANDOM[5'h11][11:10];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :148:33
        responseByte = _RANDOM[5'h11][13:12];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :149:33
        atomicResponseValid = _RANDOM[5'h11][14];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :150:38
        atomicResponseByte = _RANDOM[5'h11][16:15];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :151:39
        responseValid_1 = _RANDOM[5'h11][17];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :147:32
        responseLane_1 = _RANDOM[5'h11][19:18];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :148:33
        responseByte_1 = _RANDOM[5'h11][21:20];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :149:33
        atomicResponseValid_1 = _RANDOM[5'h11][22];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :150:38
        atomicResponseByte_1 = _RANDOM[5'h11][24:23];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :151:39
        responseValid_2 = _RANDOM[5'h11][25];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :147:32
        responseLane_2 = _RANDOM[5'h11][27:26];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :148:33
        responseByte_2 = _RANDOM[5'h11][29:28];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :149:33
        atomicResponseValid_2 = _RANDOM[5'h11][30];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :150:38
        atomicResponseByte_2 = {_RANDOM[5'h11][31], _RANDOM[5'h12][0]};	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :66:35, :151:39
        responseValid_3 = _RANDOM[5'h12][1];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :147:32, :151:39
        responseLane_3 = _RANDOM[5'h12][3:2];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :148:33, :151:39
        responseByte_3 = _RANDOM[5'h12][5:4];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :149:33, :151:39
        atomicResponseValid_3 = _RANDOM[5'h12][6];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :150:38, :151:39
        atomicResponseByte_3 = _RANDOM[5'h12][8:7];	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :151:39
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  banks_64x8 banks_0_ext (	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
    .R0_addr (issueAtomicRead ? _atomicBankAddress_T[7:2] : _selectedOffset_T_2[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :143:60, :145:34
    .R0_en   (issueVectorRead | issueAtomicRead),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :143:60, :144:37
    .R0_clk  (clock),
    .R0_data (_banks_0_ext_R0_data),
    .W0_addr (issueAtomicWrite ? _atomicBankAddress_T[7:2] : _selectedOffset_T_2[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :163:41, :164:27
    .W0_en   (issueAtomicWrite | (|candidateBits) & transaction_isStore),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :161:41, :163:41, :169:27
    .W0_clk  (clock),
    .W0_data (issueAtomicWrite ? _atomicWriteData_T_1[7:0] : _vectorWriteData_T_1[7:0])	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:163:41, :166:{44,67}, :168:{23,44}, :172:12
  );	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  banks_64x8 banks_1_ext (	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
    .R0_addr (issueAtomicRead_1 ? _atomicBankAddress_T_2[7:2] : _selectedOffset_T_5[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :143:60, :145:34
    .R0_en   (readIssued_1 | issueAtomicRead_1),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :143:60, :144:37
    .R0_clk  (clock),
    .R0_data (_banks_1_ext_R0_data),
    .W0_addr
      (issueAtomicWrite_1 ? _atomicBankAddress_T_2[7:2] : _selectedOffset_T_5[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :163:41, :164:27
    .W0_en   (issueAtomicWrite_1 | (|candidateBits_1) & transaction_isStore),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :161:41, :163:41, :169:27
    .W0_clk  (clock),
    .W0_data (issueAtomicWrite_1 ? _atomicWriteData_T_3[7:0] : _vectorWriteData_T_3[7:0])	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:163:41, :166:{44,67}, :168:{23,44}, :172:12
  );	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  banks_64x8 banks_2_ext (	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
    .R0_addr (issueAtomicRead_2 ? _atomicBankAddress_T_4[7:2] : _selectedOffset_T_8[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :143:60, :145:34
    .R0_en   (readIssued_2 | issueAtomicRead_2),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :143:60, :144:37
    .R0_clk  (clock),
    .R0_data (_banks_2_ext_R0_data),
    .W0_addr
      (issueAtomicWrite_2 ? _atomicBankAddress_T_4[7:2] : _selectedOffset_T_8[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :163:41, :164:27
    .W0_en   (issueAtomicWrite_2 | (|candidateBits_2) & transaction_isStore),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :161:41, :163:41, :169:27
    .W0_clk  (clock),
    .W0_data (issueAtomicWrite_2 ? _atomicWriteData_T_5[7:0] : _vectorWriteData_T_5[7:0])	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:163:41, :166:{44,67}, :168:{23,44}, :172:12
  );	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  banks_64x8 banks_3_ext (	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
    .R0_addr
      (issueAtomicRead_3 ? _atomicBankAddress_T_6[7:2] : _selectedOffset_T_11[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :143:60, :145:34
    .R0_en   (readIssued_3 | issueAtomicRead_3),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:132:40, :143:60, :144:37
    .R0_clk  (clock),
    .R0_data (_banks_3_ext_R0_data),
    .W0_addr
      (issueAtomicWrite_3 ? _atomicBankAddress_T_6[7:2] : _selectedOffset_T_11[7:2]),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:128:{43,71}, :129:38, :142:{43,57}, :163:41, :164:27
    .W0_en   (issueAtomicWrite_3 | (|candidateBits_3) & transaction_isStore),	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:54:32, :122:36, :123:38, :161:41, :163:41, :169:27
    .W0_clk  (clock),
    .W0_data (issueAtomicWrite_3 ? _atomicWriteData_T_7[7:0] : _vectorWriteData_T_7[7:0])	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:163:41, :166:{44,67}, :168:{23,44}, :172:12
  );	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:53:16
  assign io_in_ready = io_in_ready_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :69:{24,40,76}
  assign io_out_valid = outputValid;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :59:36
  assign io_out_bits_readData_0 = result_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
  assign io_out_bits_readData_1 = result_1;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
  assign io_out_bits_readData_2 = result_2;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
  assign io_out_bits_readData_3 = result_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :57:31
  assign io_out_bits_faultMask = faultMask;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :58:34
  assign io_atomicIn_ready = io_atomicIn_ready_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :71:{30,46}
  assign io_atomicOut_valid = io_atomicOut_valid_0;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :234:37
  assign io_atomicOut_bits_oldValue = atomicOldValue;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :65:35
  assign io_atomicOut_bits_fault = atomicFault;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :67:36
  assign io_idle = ~busy & ~outputValid & _io_idle_T_3;	// src/main/scala/opengpu/core/memory/BankedSharedMemory.scala:39:7, :56:29, :59:36, :69:{18,27,55}, :242:{20,36}
endmodule

