// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module JobDispatcher(	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
  input         clock,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
                reset,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
  output        io_launch_ready,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  input         io_launch_valid,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  input  [31:0] io_launch_bits_kernelPc,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_kernargAddress,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_gridSize_0,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_gridSize_1,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_gridSize_2,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  input  [15:0] io_launch_bits_localSize_0,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_localSize_1,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_launch_bits_localSize_2,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  input         io_workgroup_ready,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output        io_workgroup_valid,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output [31:0] io_workgroup_bits_kernelPc,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroup_bits_kernargAddress,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output [15:0] io_workgroup_bits_localSize_0,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroup_bits_localSize_1,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroup_bits_localSize_2,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output [31:0] io_workgroup_bits_groupId_0,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroup_bits_groupId_1,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroup_bits_groupId_2,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output        io_workgroupCompletion_ready,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  input         io_workgroupCompletion_valid,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_workgroupCompletion_bits_success,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_completion_ready,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
  output        io_completion_valid,	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
                io_completion_bits_success	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:14:14
);

  reg  [1:0]  state;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30
  reg  [31:0] command_kernelPc;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [31:0] command_kernargAddress;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [31:0] command_gridSize_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [31:0] command_gridSize_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [31:0] command_gridSize_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [15:0] command_localSize_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [15:0] command_localSize_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [15:0] command_localSize_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
  reg  [31:0] groupId_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
  reg  [31:0] groupId_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
  reg  [31:0] groupId_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
  reg         accumulatedSuccess;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:25:43
  wire        io_launch_ready_0 = state == 2'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :28:28
  wire        io_workgroup_valid_0 = state == 2'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :29:31
  wire        io_workgroupCompletion_ready_0 = state == 2'h2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :35:41
  wire        nonEmptyGrid =
    (|io_launch_bits_gridSize_0) & (|io_launch_bits_gridSize_1)
    & (|io_launch_bits_gridSize_2);	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:27:{60,78}
  wire [31:0] _lastX_T = command_gridSize_0 - 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28, :39:58
  wire [31:0] _lastY_T = command_gridSize_1 - 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28, :40:58
  wire        lastGroup =
    groupId_0 == _lastX_T & groupId_1 == _lastY_T & groupId_2 == command_gridSize_2
    - 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28, :24:32, :39:{34,58}, :40:{34,58}, :41:{34,58}, :42:{33,42}
  wire        _GEN = io_workgroupCompletion_ready_0 & io_workgroupCompletion_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:35:41
  wire        _GEN_0 = groupId_0 == _lastX_T;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32, :39:{34,58}, :60:{12,20}, :61:20, :63:20
  wire        _GEN_1 = groupId_1 == _lastY_T;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32, :40:{34,58}, :64:{14,22}, :65:22, :67:22
  wire        _GEN_2 = io_launch_ready_0 & io_launch_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:28:28
  always @(posedge clock) begin	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
    if (reset) begin	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      state <= 2'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30
      groupId_0 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      groupId_1 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      groupId_2 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      accumulatedSuccess <= 1'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:25:43
    end
    else begin	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      if (io_completion_ready & (&state))	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :36:32
        state <= 2'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30
      else if (_GEN)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        state <= {lastGroup, 1'h1};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :42:{33,42}, :57:21, :58:13, :71:13
      else if (io_workgroup_ready & io_workgroup_valid_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:29:31
        state <= 2'h2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :35:41
      else if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        state <= {~nonEmptyGrid, 1'h1};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:22:30, :27:78, :48:17
      if (~_GEN | lastGroup) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:42:{33,42}, :44:24, :55:37, :57:21
        if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
          groupId_0 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      end
      else	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:44:24, :55:37, :57:21
        groupId_0 <= _GEN_0 ? 32'h0 : groupId_0 + 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32, :39:34, :60:{12,20}, :61:{20,34}, :63:20
      if (~_GEN | lastGroup | ~_GEN_0) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:39:34, :42:{33,42}, :44:24, :55:37, :57:21, :60:{12,20}, :61:20, :63:20
        if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
          groupId_1 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      end
      else	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:44:24, :55:37, :57:21, :60:20
        groupId_1 <= _GEN_1 ? 32'h0 : groupId_1 + 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32, :40:34, :64:{14,22}, :65:{22,36}, :67:22
      if (~_GEN | lastGroup | ~(_GEN_0 & _GEN_1)) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/dispatch/JobDispatcher.scala:39:34, :40:34, :42:{33,42}, :44:24, :55:37, :57:21, :60:{12,20}, :61:20, :63:20, :64:{14,22}, :65:22, :67:22, :68:22
        if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
          groupId_2 <= 32'h0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32
      end
      else	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:44:24, :55:37, :57:21, :60:20
        groupId_2 <= groupId_2 + 32'h1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:24:32, :68:36
      if (_GEN)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        accumulatedSuccess <= accumulatedSuccess & io_workgroupCompletion_bits_success;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:25:43, :56:46
      else if (_GEN_2)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        accumulatedSuccess <= nonEmptyGrid;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:25:43, :27:78
    end
    if (_GEN_2) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      command_kernelPc <= io_launch_bits_kernelPc;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_kernargAddress <= io_launch_bits_kernargAddress;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_gridSize_0 <= io_launch_bits_gridSize_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_gridSize_1 <= io_launch_bits_gridSize_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_gridSize_2 <= io_launch_bits_gridSize_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_localSize_0 <= io_launch_bits_localSize_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_localSize_1 <= io_launch_bits_localSize_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
      command_localSize_2 <= io_launch_bits_localSize_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:23:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:9];	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
    initial begin	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
        end	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
        state = _RANDOM[4'h0][1:0];	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :22:30
        command_kernelPc = {_RANDOM[4'h0][31:2], _RANDOM[4'h1][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :22:30, :23:28
        command_kernargAddress = {_RANDOM[4'h1][31:2], _RANDOM[4'h2][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_gridSize_0 = {_RANDOM[4'h2][31:2], _RANDOM[4'h3][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_gridSize_1 = {_RANDOM[4'h3][31:2], _RANDOM[4'h4][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_gridSize_2 = {_RANDOM[4'h4][31:2], _RANDOM[4'h5][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_localSize_0 = _RANDOM[4'h5][17:2];	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_localSize_1 = {_RANDOM[4'h5][31:18], _RANDOM[4'h6][1:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        command_localSize_2 = _RANDOM[4'h6][17:2];	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
        groupId_0 = {_RANDOM[4'h6][31:18], _RANDOM[4'h7][17:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28, :24:32
        groupId_1 = {_RANDOM[4'h7][31:18], _RANDOM[4'h8][17:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32
        groupId_2 = {_RANDOM[4'h8][31:18], _RANDOM[4'h9][17:0]};	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32
        accumulatedSuccess = _RANDOM[4'h9][18];	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32, :25:43
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_launch_ready = io_launch_ready_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :28:28
  assign io_workgroup_valid = io_workgroup_valid_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :29:31
  assign io_workgroup_bits_kernelPc = command_kernelPc;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
  assign io_workgroup_bits_kernargAddress = command_kernargAddress;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
  assign io_workgroup_bits_localSize_0 = command_localSize_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
  assign io_workgroup_bits_localSize_1 = command_localSize_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
  assign io_workgroup_bits_localSize_2 = command_localSize_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :23:28
  assign io_workgroup_bits_groupId_0 = groupId_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32
  assign io_workgroup_bits_groupId_1 = groupId_1;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32
  assign io_workgroup_bits_groupId_2 = groupId_2;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :24:32
  assign io_workgroupCompletion_ready = io_workgroupCompletion_ready_0;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :35:41
  assign io_completion_valid = &state;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :22:30, :36:32
  assign io_completion_bits_success = accumulatedSuccess;	// src/main/scala/opengpu/dispatch/JobDispatcher.scala:13:7, :25:43
endmodule

