// Generated by CIRCT firtool-1.133.0
module L2SramArray_2(	// src/main/scala/opengpu/core/memory/L2SramArray.scala:40:7
  input          clock,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:40:7
                 io_readEnable,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
  input  [2:0]   io_readAddress,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
  output [511:0] io_readData,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
  input          io_writeEnable,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
  input  [2:0]   io_writeAddress,	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
  input  [511:0] io_writeData	// src/main/scala/opengpu/core/memory/L2SramArray.scala:49:14
);

  wire readEnable;	// src/main/scala/opengpu/core/memory/L2SramArray.scala:92:37
  assign readEnable = io_readEnable & ~io_writeEnable;	// src/main/scala/opengpu/core/memory/L2SramArray.scala:92:{37,40}
  memory_8x512 memory_ext (	// src/main/scala/opengpu/core/memory/L2SramArray.scala:90:29
    .RW0_addr  (io_writeEnable ? io_writeAddress : io_readAddress),	// src/main/scala/opengpu/core/memory/L2SramArray.scala:90:29
    .RW0_en    (readEnable | io_writeEnable),	// src/main/scala/opengpu/core/memory/L2SramArray.scala:90:29, :92:37
    .RW0_clk   (clock),
    .RW0_wmode (io_writeEnable),
    .RW0_wdata (io_writeData),
    .RW0_rdata (io_readData)
  );	// src/main/scala/opengpu/core/memory/L2SramArray.scala:90:29
endmodule

