// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue8_KernelCommand(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input         clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [3:0]  io_enq_bits_commandId,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0] io_enq_bits_launch_kernelPc,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_kernargAddress,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_gridSize_0,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_gridSize_1,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_gridSize_2,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [15:0] io_enq_bits_launch_localSize_0,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_localSize_1,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_enq_bits_launch_localSize_2,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_bits_waitForDma,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [1:0]  io_enq_bits_dmaSource,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [3:0]  io_enq_bits_dmaDescriptorId,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [3:0]  io_deq_bits_commandId,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0] io_deq_bits_launch_kernelPc,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_kernargAddress,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_gridSize_0,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_gridSize_1,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_gridSize_2,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [15:0] io_deq_bits_launch_localSize_0,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_localSize_1,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_deq_bits_launch_localSize_2,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_bits_waitForDma,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [1:0]  io_deq_bits_dmaSource,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [3:0]  io_deq_bits_dmaDescriptorId,	// src/main/scala/chisel3/util/Queue.scala:72:14
                io_count	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  wire [218:0] _ram_ext_R0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  reg  [2:0]   enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0]   deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg          maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire         ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire         empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire         full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire         do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_enq != do_deq)	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][5:3];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ram_8x219 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Queue.scala:60:7
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_commandId,
        io_enq_bits_launch_kernelPc,
        io_enq_bits_launch_kernargAddress,
        io_enq_bits_launch_gridSize_2,
        io_enq_bits_launch_gridSize_1,
        io_enq_bits_launch_gridSize_0,
        io_enq_bits_launch_localSize_2,
        io_enq_bits_launch_localSize_1,
        io_enq_bits_launch_localSize_0,
        io_enq_bits_waitForDma,
        io_enq_bits_dmaSource,
        io_enq_bits_dmaDescriptorId})	// src/main/scala/chisel3/util/Queue.scala:73:91
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
  assign io_deq_bits_commandId = _ram_ext_R0_data[218:215];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_kernelPc = _ram_ext_R0_data[214:183];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_kernargAddress = _ram_ext_R0_data[182:151];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_gridSize_0 = _ram_ext_R0_data[86:55];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_gridSize_1 = _ram_ext_R0_data[118:87];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_gridSize_2 = _ram_ext_R0_data[150:119];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_localSize_0 = _ram_ext_R0_data[22:7];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_localSize_1 = _ram_ext_R0_data[38:23];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_launch_localSize_2 = _ram_ext_R0_data[54:39];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_waitForDma = _ram_ext_R0_data[6];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_dmaSource = _ram_ext_R0_data[5:4];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_deq_bits_dmaDescriptorId = _ram_ext_R0_data[3:0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:91
  assign io_count = {full, enq_ptr_value - deq_ptr_value};	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :126:32, :129:62
endmodule

