// Generated by CIRCT firtool-1.133.0
module RRArbiter1_CacheLineInvalidate(	// src/main/scala/chisel3/util/Arbiter.scala:127:7
  output        io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input  [31:0] io_in_0_bits_lineAddress,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  input         io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:52:14
  output [31:0] io_out_bits_lineAddress	// src/main/scala/chisel3/util/Arbiter.scala:52:14
);

  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:127:7
  assign io_out_valid = io_in_0_valid;	// src/main/scala/chisel3/util/Arbiter.scala:127:7
  assign io_out_bits_lineAddress = io_in_0_bits_lineAddress;	// src/main/scala/chisel3/util/Arbiter.scala:127:7
endmodule

