// Generated by CIRCT firtool-1.133.0
module SharedComputeMemoryInterconnect(	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
  output         io_cuRequest_0_ready,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_cuRequest_0_valid,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [31:0]  io_cuRequest_0_bits_address,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [511:0] io_cuRequest_0_bits_writeData,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [63:0]  io_cuRequest_0_bits_byteMask,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_cuRequest_0_bits_isWrite,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [2:0]   io_cuRequest_0_bits_sizeLog2,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_cuRequest_0_bits_cacheClient,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
                 io_cuRequest_0_bits_cacheResident,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [1:0]   io_cuRequest_0_bits_transactionId,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_cuResponse_0_ready,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_cuResponse_0_valid,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [511:0] io_cuResponse_0_bits_readData,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_cuResponse_0_bits_fault,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [1:0]   io_cuResponse_0_bits_transactionId,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_memoryRequest_ready,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_memoryRequest_valid,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [31:0]  io_memoryRequest_bits_address,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [511:0] io_memoryRequest_bits_writeData,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [63:0]  io_memoryRequest_bits_byteMask,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_memoryRequest_bits_isWrite,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [2:0]   io_memoryRequest_bits_sizeLog2,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_memoryRequest_bits_cacheClient,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
                 io_memoryRequest_bits_cacheResident,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output [1:0]   io_memoryRequest_bits_transactionId,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  output         io_memoryResponse_ready,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_memoryResponse_valid,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [511:0] io_memoryResponse_bits_readData,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input          io_memoryResponse_bits_fault,	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
  input  [1:0]   io_memoryResponse_bits_transactionId	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:25:14
);

  RRArbiter1_ComputeMemoryRequest arbiter (	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:37:31
    .io_in_0_ready              (io_cuRequest_0_ready),
    .io_in_0_valid              (io_cuRequest_0_valid),
    .io_in_0_bits_address       (io_cuRequest_0_bits_address),
    .io_in_0_bits_writeData     (io_cuRequest_0_bits_writeData),
    .io_in_0_bits_byteMask      (io_cuRequest_0_bits_byteMask),
    .io_in_0_bits_isWrite       (io_cuRequest_0_bits_isWrite),
    .io_in_0_bits_sizeLog2      (io_cuRequest_0_bits_sizeLog2),
    .io_in_0_bits_cacheClient   (io_cuRequest_0_bits_cacheClient),
    .io_in_0_bits_cacheResident (io_cuRequest_0_bits_cacheResident),
    .io_in_0_bits_transactionId (io_cuRequest_0_bits_transactionId),
    .io_out_ready               (io_memoryRequest_ready),
    .io_out_valid               (io_memoryRequest_valid),
    .io_out_bits_address        (io_memoryRequest_bits_address),
    .io_out_bits_writeData      (io_memoryRequest_bits_writeData),
    .io_out_bits_byteMask       (io_memoryRequest_bits_byteMask),
    .io_out_bits_isWrite        (io_memoryRequest_bits_isWrite),
    .io_out_bits_sizeLog2       (io_memoryRequest_bits_sizeLog2),
    .io_out_bits_cacheClient    (io_memoryRequest_bits_cacheClient),
    .io_out_bits_cacheResident  (io_memoryRequest_bits_cacheResident),
    .io_out_bits_transactionId  (io_memoryRequest_bits_transactionId)
  );	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:37:31
  assign io_cuResponse_0_valid = io_memoryResponse_valid;	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
  assign io_cuResponse_0_bits_readData = io_memoryResponse_bits_readData;	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
  assign io_cuResponse_0_bits_fault = io_memoryResponse_bits_fault;	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
  assign io_cuResponse_0_bits_transactionId = io_memoryResponse_bits_transactionId;	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
  assign io_memoryResponse_ready = io_cuResponse_0_ready;	// src/main/scala/opengpu/core/memory/SharedComputeMemoryInterconnect.scala:11:7
endmodule

