// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SharedAtomicExecuteStage(	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
  input         clock,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
                reset,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
  output        io_in_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_in_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [31:0] io_in_bits_decode_instruction,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_pc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [1:0]  io_in_bits_decode_warpId,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [3:0]  io_in_bits_decode_activeMask,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_in_bits_decode_instructionAccessFault,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [2:0]  io_in_bits_decode_executionType,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_in_bits_decode_illegalInstruction,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_legal,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [4:0]  io_in_bits_decode_decoded_rs1,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_rs2,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_rd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [31:0] io_in_bits_decode_decoded_immediate,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [3:0]  io_in_bits_decode_decoded_aluOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [2:0]  io_in_bits_decode_decoded_branchOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_in_bits_decode_decoded_useImmediate,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_usePc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_useRs1,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_useRs2,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_writeRd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_memoryRead,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_memoryWrite,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_jump,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_multiply,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_divide,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_atomic,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [3:0]  io_in_bits_decode_decoded_atomicOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_in_bits_decode_decoded_csr,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_system,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_fence,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_barrier,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_texSample,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_vectorBranch,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_join,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_decode_decoded_cease,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [31:0] io_in_bits_rs1Data,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_in_bits_rs2Data,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_atomicRequest_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_atomicRequest_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_atomicRequest_bits_address,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_atomicRequest_bits_operand,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_atomicRequest_bits_operation,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_atomicResponse_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_atomicResponse_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [31:0] io_atomicResponse_bits_oldValue,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_atomicResponse_bits_fault,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_globalAtomicRequest_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_globalAtomicRequest_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [1:0]  io_globalAtomicRequest_bits_warpId,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_globalAtomicRequest_bits_address,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_globalAtomicRequest_bits_operand,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_globalAtomicRequest_bits_operation,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_globalAtomicResponse_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_globalAtomicResponse_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input  [31:0] io_globalAtomicResponse_bits_oldValue,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_globalAtomicResponse_bits_fault,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_out_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_out_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [1:0]  io_out_bits_warpId,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_out_bits_nextPc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_out_bits_activeMask,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [4:0]  io_out_bits_rd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_out_bits_data,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_fault_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_fault_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [1:0]  io_fault_bits_warpId,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_fault_bits_pc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_fault_bits_activeMask,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_fault_bits_address,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_fault_bits_misaligned,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [4:0]  io_fault_bits_rd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_fault_bits_writeRd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  input         io_unimplemented_ready,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_unimplemented_valid,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_unimplemented_bits_decode_instruction,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_pc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [1:0]  io_unimplemented_bits_decode_warpId,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_unimplemented_bits_decode_activeMask,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_unimplemented_bits_decode_instructionAccessFault,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [2:0]  io_unimplemented_bits_decode_executionType,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_unimplemented_bits_decode_illegalInstruction,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_legal,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [4:0]  io_unimplemented_bits_decode_decoded_rs1,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_rs2,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_rd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_unimplemented_bits_decode_decoded_immediate,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_unimplemented_bits_decode_decoded_aluOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [2:0]  io_unimplemented_bits_decode_decoded_branchOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_unimplemented_bits_decode_decoded_useImmediate,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_usePc,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_useRs1,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_useRs2,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_writeRd,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_memoryRead,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_memoryWrite,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_jump,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_multiply,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_divide,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_atomic,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [3:0]  io_unimplemented_bits_decode_decoded_atomicOp,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output        io_unimplemented_bits_decode_decoded_csr,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_system,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_fence,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_barrier,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_texSample,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_vectorBranch,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_join,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_decode_decoded_cease,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
  output [31:0] io_unimplemented_bits_rs1Data,	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
                io_unimplemented_bits_rs2Data	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:22:14
);

  reg  [2:0]  state;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:18:30
  reg  [31:0] instruction_decode_instruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [31:0] instruction_decode_pc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [1:0]  instruction_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [3:0]  instruction_decode_activeMask;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_instructionAccessFault;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [2:0]  instruction_decode_executionType;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_illegalInstruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_legal;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [4:0]  instruction_decode_decoded_rs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [4:0]  instruction_decode_decoded_rs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [4:0]  instruction_decode_decoded_rd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [31:0] instruction_decode_decoded_immediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [3:0]  instruction_decode_decoded_aluOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [2:0]  instruction_decode_decoded_branchOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_useImmediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_usePc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_useRs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_useRs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_writeRd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_memoryRead;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_memoryWrite;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_jump;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_multiply;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_divide;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_atomic;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [3:0]  instruction_decode_decoded_atomicOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_csr;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_system;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_fence;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_barrier;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_texSample;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_vectorBranch;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_join;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg         instruction_decode_decoded_cease;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [31:0] instruction_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [31:0] instruction_rs2Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
  reg  [31:0] oldValue;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:20:29
  reg         faultMisaligned;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:21:40
  wire        io_in_ready_0 = state == 3'h0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :37:24
  wire        io_atomicRequest_valid_0 = state == 3'h1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :45:35
  wire        io_atomicResponse_ready_0 = state == 3'h2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :52:36
  wire        io_globalAtomicRequest_valid_0 = state == 3'h3;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :59:41
  wire        io_globalAtomicResponse_ready_0 = state == 3'h4;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :66:42
  wire        io_out_valid_0 = state == 3'h5;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :73:25
  wire        io_fault_valid_0 = state == 3'h6;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :82:27
  wire        _GEN = io_in_ready_0 & io_in_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:37:24
  wire        _GEN_0 = io_atomicResponse_ready_0 & io_atomicResponse_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:52:36
  wire        _GEN_1 = io_globalAtomicResponse_ready_0 & io_globalAtomicResponse_valid;	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:66:42
  always @(posedge clock) begin	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
    if (reset) begin	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      state <= 3'h0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30
      faultMisaligned <= 1'h0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:21:40
    end
    else begin	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      if (io_unimplemented_ready & (&state) | io_fault_ready & io_fault_valid_0
          | io_out_ready & io_out_valid_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:18:30, :67:38, :73:25, :80:{21,29}, :82:27, :92:{23,31}, :94:35, :96:{31,39}
        state <= 3'h0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30
      else if (_GEN_1)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        state <= io_globalAtomicResponse_bits_fault ? 3'h6 : 3'h5;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :70:17
      else if (io_globalAtomicRequest_ready & io_globalAtomicRequest_valid_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:59:41
        state <= 3'h4;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30
      else if (_GEN_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        state <= io_atomicResponse_bits_fault ? 3'h6 : 3'h5;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :56:17
      else if (io_atomicRequest_ready & io_atomicRequest_valid_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:45:35
        state <= 3'h2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30
      else if (_GEN)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        state <=
          (|(io_in_bits_rs1Data[1:0]))
            ? 3'h6
            : {1'h0,
               ~((|(io_in_bits_rs1Data[31:28])) & io_in_bits_rs1Data < 32'h10000100),
               1'h1};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :34:{13,42}, :35:15, :40:42, :41:{17,43}, :42:10
      faultMisaligned <=
        ~(_GEN_1 | _GEN_0) & (_GEN ? (|(io_in_bits_rs1Data[1:0])) : faultMisaligned);	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35, src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:21:40, :38:20, :40:{21,42,49}, :53:32, :55:21, :67:38, :69:21
    end
    if (_GEN) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      instruction_decode_instruction <= io_in_bits_decode_instruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_pc <= io_in_bits_decode_pc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_warpId <= io_in_bits_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_activeMask <= io_in_bits_decode_activeMask;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_instructionAccessFault <=
        io_in_bits_decode_instructionAccessFault;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_executionType <= io_in_bits_decode_executionType;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_illegalInstruction <= io_in_bits_decode_illegalInstruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_legal <= io_in_bits_decode_decoded_legal;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_rs1 <= io_in_bits_decode_decoded_rs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_rs2 <= io_in_bits_decode_decoded_rs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_rd <= io_in_bits_decode_decoded_rd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_immediate <= io_in_bits_decode_decoded_immediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_aluOp <= io_in_bits_decode_decoded_aluOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_branchOp <= io_in_bits_decode_decoded_branchOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_useImmediate <= io_in_bits_decode_decoded_useImmediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_usePc <= io_in_bits_decode_decoded_usePc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_useRs1 <= io_in_bits_decode_decoded_useRs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_useRs2 <= io_in_bits_decode_decoded_useRs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_writeRd <= io_in_bits_decode_decoded_writeRd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_memoryRead <= io_in_bits_decode_decoded_memoryRead;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_memoryWrite <= io_in_bits_decode_decoded_memoryWrite;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_jump <= io_in_bits_decode_decoded_jump;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_multiply <= io_in_bits_decode_decoded_multiply;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_divide <= io_in_bits_decode_decoded_divide;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_atomic <= io_in_bits_decode_decoded_atomic;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_atomicOp <= io_in_bits_decode_decoded_atomicOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_csr <= io_in_bits_decode_decoded_csr;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_system <= io_in_bits_decode_decoded_system;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_fence <= io_in_bits_decode_decoded_fence;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_barrier <= io_in_bits_decode_decoded_barrier;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_texSample <= io_in_bits_decode_decoded_texSample;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_vectorBranch <= io_in_bits_decode_decoded_vectorBranch;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_join <= io_in_bits_decode_decoded_join;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_decode_decoded_cease <= io_in_bits_decode_decoded_cease;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_rs1Data <= io_in_bits_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
      instruction_rs2Data <= io_in_bits_rs2Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:19:32
    end
    if (_GEN_1)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      oldValue <= io_globalAtomicResponse_bits_oldValue;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:20:29
    else if (_GEN_0)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      oldValue <= io_atomicResponse_bits_oldValue;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:20:29
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
    initial begin	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
        end	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
        state = _RANDOM[3'h0][2:0];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30
        instruction_decode_instruction = {_RANDOM[3'h0][31:3], _RANDOM[3'h1][2:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :19:32
        instruction_decode_pc = {_RANDOM[3'h1][31:3], _RANDOM[3'h2][2:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_warpId = _RANDOM[3'h2][4:3];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_activeMask = _RANDOM[3'h2][8:5];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_instructionAccessFault = _RANDOM[3'h2][9];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_executionType = _RANDOM[3'h2][12:10];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_illegalInstruction = _RANDOM[3'h2][13];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_legal = _RANDOM[3'h2][14];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_rs1 = _RANDOM[3'h2][19:15];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_rs2 = _RANDOM[3'h2][24:20];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_rd = _RANDOM[3'h2][29:25];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_immediate =
          {_RANDOM[3'h2][31:30], _RANDOM[3'h3][29:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_aluOp = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][1:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_branchOp = _RANDOM[3'h4][4:2];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_useImmediate = _RANDOM[3'h4][5];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_usePc = _RANDOM[3'h4][6];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_useRs1 = _RANDOM[3'h4][7];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_useRs2 = _RANDOM[3'h4][8];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_writeRd = _RANDOM[3'h4][9];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_memoryRead = _RANDOM[3'h4][10];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_memoryWrite = _RANDOM[3'h4][11];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_jump = _RANDOM[3'h4][12];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_multiply = _RANDOM[3'h4][13];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_divide = _RANDOM[3'h4][14];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_atomic = _RANDOM[3'h4][15];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_atomicOp = _RANDOM[3'h4][19:16];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_csr = _RANDOM[3'h4][20];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_system = _RANDOM[3'h4][21];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_fence = _RANDOM[3'h4][22];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_barrier = _RANDOM[3'h4][23];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_texSample = _RANDOM[3'h4][24];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_vectorBranch = _RANDOM[3'h4][25];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_join = _RANDOM[3'h4][26];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_decode_decoded_cease = _RANDOM[3'h4][27];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_rs1Data = {_RANDOM[3'h4][31:28], _RANDOM[3'h5][27:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        instruction_rs2Data = {_RANDOM[3'h5][31:28], _RANDOM[3'h6][27:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
        oldValue = {_RANDOM[3'h6][31:28], _RANDOM[3'h7][27:0]};	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32, :20:29
        faultMisaligned = _RANDOM[3'h7][28];	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :20:29, :21:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = io_in_ready_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :37:24
  assign io_atomicRequest_valid = io_atomicRequest_valid_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :45:35
  assign io_atomicRequest_bits_address = instruction_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_atomicRequest_bits_operand = instruction_rs2Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_atomicRequest_bits_operation = instruction_decode_decoded_atomicOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_atomicResponse_ready = io_atomicResponse_ready_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :52:36
  assign io_globalAtomicRequest_valid = io_globalAtomicRequest_valid_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :59:41
  assign io_globalAtomicRequest_bits_warpId = instruction_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_globalAtomicRequest_bits_address = instruction_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_globalAtomicRequest_bits_operand = instruction_rs2Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_globalAtomicRequest_bits_operation = instruction_decode_decoded_atomicOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_globalAtomicResponse_ready = io_globalAtomicResponse_ready_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :66:42
  assign io_out_valid = io_out_valid_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :73:25
  assign io_out_bits_warpId = instruction_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_out_bits_nextPc = instruction_decode_pc + 32'h4;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32, :75:47
  assign io_out_bits_activeMask = instruction_decode_activeMask;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_out_bits_rd = instruction_decode_decoded_rd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_out_bits_data = oldValue;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :20:29
  assign io_fault_valid = io_fault_valid_0;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :82:27
  assign io_fault_bits_warpId = instruction_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_fault_bits_pc = instruction_decode_pc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_fault_bits_activeMask = instruction_decode_activeMask;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_fault_bits_address = instruction_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_fault_bits_misaligned = faultMisaligned;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :21:40
  assign io_fault_bits_rd = instruction_decode_decoded_rd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_fault_bits_writeRd = instruction_decode_decoded_writeRd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_valid = &state;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :18:30, :94:35
  assign io_unimplemented_bits_decode_instruction = instruction_decode_instruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_pc = instruction_decode_pc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_warpId = instruction_decode_warpId;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_activeMask = instruction_decode_activeMask;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_instructionAccessFault =
    instruction_decode_instructionAccessFault;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_executionType = instruction_decode_executionType;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_illegalInstruction =
    instruction_decode_illegalInstruction;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_legal = instruction_decode_decoded_legal;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_rs1 = instruction_decode_decoded_rs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_rs2 = instruction_decode_decoded_rs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_rd = instruction_decode_decoded_rd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_immediate =
    instruction_decode_decoded_immediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_aluOp = instruction_decode_decoded_aluOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_branchOp =
    instruction_decode_decoded_branchOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_useImmediate =
    instruction_decode_decoded_useImmediate;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_usePc = instruction_decode_decoded_usePc;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_useRs1 = instruction_decode_decoded_useRs1;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_useRs2 = instruction_decode_decoded_useRs2;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_writeRd =
    instruction_decode_decoded_writeRd;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_memoryRead =
    instruction_decode_decoded_memoryRead;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_memoryWrite =
    instruction_decode_decoded_memoryWrite;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_jump = instruction_decode_decoded_jump;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_multiply =
    instruction_decode_decoded_multiply;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_divide = instruction_decode_decoded_divide;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_atomic = instruction_decode_decoded_atomic;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_atomicOp =
    instruction_decode_decoded_atomicOp;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_csr = instruction_decode_decoded_csr;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_system = instruction_decode_decoded_system;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_fence = instruction_decode_decoded_fence;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_barrier =
    instruction_decode_decoded_barrier;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_texSample =
    instruction_decode_decoded_texSample;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_vectorBranch =
    instruction_decode_decoded_vectorBranch;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_join = instruction_decode_decoded_join;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_decode_decoded_cease = instruction_decode_decoded_cease;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_rs1Data = instruction_rs1Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
  assign io_unimplemented_bits_rs2Data = instruction_rs2Data;	// src/main/scala/opengpu/core/execute/memory/SharedAtomicExecuteStage.scala:15:7, :19:32
endmodule

