// Generated by CIRCT firtool-1.133.0
module SimtFrontendControl(	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:17:7
  input         clock,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:17:7
                reset,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:17:7
  output        io_launch_ready,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_launch_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [1:0]  io_launch_bits_warpId,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [31:0] io_launch_bits_startPc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [3:0]  io_launch_bits_activeMask,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_issue_ready,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output        io_issue_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output [1:0]  io_issue_bits_warpId,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output [31:0] io_issue_bits_pc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output [3:0]  io_issue_bits_activeMask,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output        io_branch_ready,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_branch_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [1:0]  io_branch_bits_warpId,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [31:0] io_branch_bits_targetPc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
                io_branch_bits_fallthroughPc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
                io_branch_bits_reconvergePc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [3:0]  io_branch_bits_activeMask,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
                io_branch_bits_takenMask,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output        io_scalarRedirect_ready,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_scalarRedirect_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [1:0]  io_scalarRedirect_bits_warpId,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [31:0] io_scalarRedirect_bits_pc,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [3:0]  io_scalarRedirect_bits_activeMask,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output        io_restore_ready,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_restore_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [1:0]  io_restore_bits,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input         io_finish_valid,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  input  [1:0]  io_finish_bits,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
  output [3:0]  io_active,	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
                io_blocked	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:20:14
);

  wire        _controlFlow_io_current_valid;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [1:0]  _controlFlow_io_current_bits_warpId;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [31:0] _controlFlow_io_current_bits_pc;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [3:0]  _controlFlow_io_current_bits_activeMask;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire        _controlFlow_io_restore_valid;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [1:0]  _controlFlow_io_restore_bits_warpId;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [31:0] _controlFlow_io_restore_bits_pc;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire [3:0]  _controlFlow_io_restore_bits_activeMask;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  wire        restorePathValid =
    io_restore_valid & _controlFlow_io_restore_valid & ~_controlFlow_io_current_valid;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35, :41:{22,54}, :42:7
  WarpScheduler scheduler (	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:32:33
    .clock                     (clock),
    .reset                     (reset),
    .io_launch_ready           (io_launch_ready),
    .io_launch_valid           (io_launch_valid),
    .io_launch_bits_warpId     (io_launch_bits_warpId),
    .io_launch_bits_startPc    (io_launch_bits_startPc),
    .io_launch_bits_activeMask (io_launch_bits_activeMask),
    .io_issue_ready            (io_issue_ready),
    .io_issue_valid            (io_issue_valid),
    .io_issue_bits_warpId      (io_issue_bits_warpId),
    .io_issue_bits_pc          (io_issue_bits_pc),
    .io_issue_bits_activeMask  (io_issue_bits_activeMask),
    .io_resume_valid
      (_controlFlow_io_current_valid | restorePathValid | io_scalarRedirect_valid),	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35, :41:{22,54}, :51:{34,54}
    .io_resume_bits_warpId
      (_controlFlow_io_current_valid
         ? _controlFlow_io_current_bits_warpId
         : restorePathValid
             ? _controlFlow_io_restore_bits_warpId
             : io_scalarRedirect_bits_warpId),	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35, :41:{22,54}, :54:8, :57:10
    .io_resume_bits_nextPc
      (_controlFlow_io_current_valid
         ? _controlFlow_io_current_bits_pc
         : restorePathValid
             ? _controlFlow_io_restore_bits_pc
             : io_scalarRedirect_bits_pc),	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35, :41:{22,54}, :64:8, :67:10
    .io_resume_bits_activeMask
      (_controlFlow_io_current_valid
         ? _controlFlow_io_current_bits_activeMask
         : restorePathValid
             ? _controlFlow_io_restore_bits_activeMask
             : io_scalarRedirect_bits_activeMask),	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35, :41:{22,54}, :74:8, :77:10
    .io_finish_valid           (io_finish_valid),
    .io_finish_bits            (io_finish_bits),
    .io_active                 (io_active),
    .io_blocked                (io_blocked)
  );	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:32:33
  SimtControlFlow controlFlow (	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
    .clock                        (clock),
    .reset                        (reset),
    .io_branch_ready              (io_branch_ready),
    .io_branch_valid              (io_branch_valid),
    .io_branch_bits_warpId        (io_branch_bits_warpId),
    .io_branch_bits_targetPc      (io_branch_bits_targetPc),
    .io_branch_bits_fallthroughPc (io_branch_bits_fallthroughPc),
    .io_branch_bits_reconvergePc  (io_branch_bits_reconvergePc),
    .io_branch_bits_activeMask    (io_branch_bits_activeMask),
    .io_branch_bits_takenMask     (io_branch_bits_takenMask),
    .io_current_valid             (_controlFlow_io_current_valid),
    .io_current_bits_warpId       (_controlFlow_io_current_bits_warpId),
    .io_current_bits_pc           (_controlFlow_io_current_bits_pc),
    .io_current_bits_activeMask   (_controlFlow_io_current_bits_activeMask),
    .io_restoreWarpId             (io_restore_bits),
    .io_restore_ready             (restorePathValid),	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:41:{22,54}
    .io_restore_valid             (_controlFlow_io_restore_valid),
    .io_restore_bits_warpId       (_controlFlow_io_restore_bits_warpId),
    .io_restore_bits_pc           (_controlFlow_io_restore_bits_pc),
    .io_restore_bits_activeMask   (_controlFlow_io_restore_bits_activeMask),
    .io_clear_valid               (io_finish_valid),
    .io_clear_bits                (io_finish_bits)
  );	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:33:35
  assign io_scalarRedirect_ready = ~_controlFlow_io_current_valid & ~restorePathValid;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:17:7, :33:35, :41:{22,54}, :42:7, :49:{35,38}
  assign io_restore_ready =
    _controlFlow_io_restore_valid & ~_controlFlow_io_current_valid;	// src/main/scala/opengpu/core/frontend/SimtFrontendControl.scala:17:7, :33:35, :42:7, :44:34
endmodule

