// Generated by CIRCT firtool-1.133.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module VectorFpuAlu(	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
  input         clock,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
                reset,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
  output        io_in_ready,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input         io_in_valid,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [1:0]  io_in_bits_warpId,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [31:0] io_in_bits_pc,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [3:0]  io_in_bits_warpActiveMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [4:0]  io_in_bits_vd,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [3:0]  io_in_bits_activeMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_rawActiveMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_predicateMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [31:0] io_in_bits_oldVd_0,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_oldVd_1,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_oldVd_2,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_oldVd_3,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs1_0,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs1_1,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs1_2,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs1_3,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs2_0,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs2_1,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs2_2,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_vs2_3,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_in_bits_scalarFpData,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [5:0]  io_in_bits_funct6,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input  [2:0]  io_in_bits_operandType,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  input         io_in_bits_vm,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_out_ready,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output        io_out_valid,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [1:0]  io_out_bits_warpId,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [31:0] io_out_bits_pc,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [3:0]  io_out_bits_warpActiveMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [4:0]  io_out_bits_vd,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [31:0] io_out_bits_data_0,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_out_bits_data_1,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_out_bits_data_2,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
                io_out_bits_data_3,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [3:0]  io_out_bits_mask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output        io_out_bits_writesMask,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output [4:0]  io_out_bits_flags,	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
  output        io_out_bits_writesFlags	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:67:14
);

  reg         inputValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35
  reg  [1:0]  inputBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [3:0]  inputBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [4:0]  inputBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [3:0]  inputBits_activeMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [3:0]  inputBits_rawActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [3:0]  inputBits_predicateMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_oldVd_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_oldVd_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_oldVd_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_oldVd_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs1_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs1_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs1_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs1_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs2_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs2_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs2_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_vs2_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [31:0] inputBits_scalarFpData;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [5:0]  inputBits_funct6;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg  [2:0]  inputBits_operandType;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg         inputBits_vm;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
  reg         candidateValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:74:39
  reg  [1:0]  candidateBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [3:0]  candidateBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [4:0]  candidateBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [5:0]  candidateBits_funct6;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_vm;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_scalarFpData;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_oldVd_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_oldVd_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_oldVd_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_oldVd_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_lhs_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_lhs_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_lhs_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_lhs_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_rhs_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_rhs_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_rhs_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [31:0] candidateBits_rhs_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [3:0]  candidateBits_enabled;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [3:0]  candidateBits_rawActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg  [3:0]  candidateBits_predicateMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsLess_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsLess_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsLess_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsLess_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsGreater_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsGreater_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsGreater_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_lhsGreater_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_equal_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_equal_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_equal_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_equal_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_unordered_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_unordered_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_unordered_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         candidateBits_unordered_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34
  reg         outputValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:76:36
  reg  [1:0]  outputBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [31:0] outputBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [3:0]  outputBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [4:0]  outputBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [31:0] outputBits_data_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [31:0] outputBits_data_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [31:0] outputBits_data_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [31:0] outputBits_data_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [3:0]  outputBits_mask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg         outputBits_writesMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg  [4:0]  outputBits_flags;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  reg         outputBits_writesFlags;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31
  wire        outputReady = ~outputValid | io_out_ready;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:76:36, :78:{29,42}
  wire        candidateReady = ~candidateValid | outputReady;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:74:39, :78:42, :79:{32,48}
  wire        inputReady = ~inputValid | candidateReady;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35, :79:48, :80:{28,40}
  wire        isFvf = inputBits_operandType == 3'h5;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :195:43
  wire [31:0] rhs = isFvf ? inputBits_scalarFpData : inputBits_vs1_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :195:43, :196:22
  wire        _candidateBits_equal_0_T_1 = inputBits_vs2_0[31] == rhs[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :201:30, :202:30, :206:23
  wire        _lhsGreater_T_2 = inputBits_vs2_0[30:0] > rhs[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:35
  wire        _lhsGreater_T_1 = inputBits_vs2_0[30:0] < rhs[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:52
  wire [31:0] rhs_1 = isFvf ? inputBits_scalarFpData : inputBits_vs1_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :195:43, :196:22
  wire        _candidateBits_equal_1_T_1 = inputBits_vs2_1[31] == rhs_1[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :201:30, :202:30, :206:23
  wire        _lhsGreater_T_8 = inputBits_vs2_1[30:0] > rhs_1[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:35
  wire        _lhsGreater_T_7 = inputBits_vs2_1[30:0] < rhs_1[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:52
  wire [31:0] rhs_2 = isFvf ? inputBits_scalarFpData : inputBits_vs1_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :195:43, :196:22
  wire        _candidateBits_equal_2_T_1 = inputBits_vs2_2[31] == rhs_2[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :201:30, :202:30, :206:23
  wire        _lhsGreater_T_14 = inputBits_vs2_2[30:0] > rhs_2[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:35
  wire        _lhsGreater_T_13 = inputBits_vs2_2[30:0] < rhs_2[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:52
  wire [31:0] rhs_3 = isFvf ? inputBits_scalarFpData : inputBits_vs1_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :195:43, :196:22
  wire        _candidateBits_equal_3_T_1 = inputBits_vs2_3[31] == rhs_3[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :201:30, :202:30, :206:23
  wire        _lhsGreater_T_20 = inputBits_vs2_3[30:0] > rhs_3[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:35
  wire        _lhsGreater_T_19 = inputBits_vs2_3[30:0] < rhs_3[30:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :196:22, :203:25, :204:25, :207:52
  wire        _minMaxData_T_15 = candidateBits_funct6 == 6'h4;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :87:26
  wire        isMinMax = _minMaxData_T_15 | candidateBits_funct6 == 6'h6;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :87:{26,38,62}
  wire        isCompare = candidateBits_funct6 > 6'h17 & ~(candidateBits_funct6[5]);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :89:{26,37,61}
  wire        isFpMerge = candidateBits_funct6 == 6'h17;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :90:48
  wire        _signData_T_47 = candidateBits_funct6 == 6'h8;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :103:56
  wire        _signData_T_49 = candidateBits_funct6 == 6'h9;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :103:56
  wire        _signData_T_51 = candidateBits_funct6 == 6'hA;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :103:56
  wire        _comparison_T_51 = candidateBits_funct6 == 6'h18;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _comparison_T_53 = candidateBits_funct6 == 6'h19;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _comparison_T_55 = candidateBits_funct6 == 6'h1B;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _comparison_T_57 = candidateBits_funct6 == 6'h1C;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _comparison_T_59 = candidateBits_funct6 == 6'h1D;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _comparison_T_61 = candidateBits_funct6 == 6'h1F;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :117:62
  wire        _outputBits_writesFlags_T = isMinMax | isCompare;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:87:38, :89:37, :155:41
  always @(posedge clock) begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
    if (reset) begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      inputValid <= 1'h0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35
      candidateValid <= 1'h0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35, :74:39
      outputValid <= 1'h0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35, :76:36
    end
    else begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      if (inputReady)	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:80:40
        inputValid <= io_in_valid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35
      if (candidateReady)	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:79:48
        candidateValid <= inputValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35, :74:39
      if (outputReady)	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:78:42
        outputValid <= candidateValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:74:39, :76:36
    end
    if (inputReady & io_in_valid) begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :80:40, :227:20, :229:23, :230:24
      inputBits_warpId <= io_in_bits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_pc <= io_in_bits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_warpActiveMask <= io_in_bits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vd <= io_in_bits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_activeMask <=
        io_in_bits_activeMask & (io_in_bits_vm ? 4'hF : io_in_bits_predicateMask);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :243:31, :244:{14,34}
      inputBits_rawActiveMask <= io_in_bits_rawActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_predicateMask <= io_in_bits_predicateMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_oldVd_0 <= io_in_bits_oldVd_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_oldVd_1 <= io_in_bits_oldVd_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_oldVd_2 <= io_in_bits_oldVd_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_oldVd_3 <= io_in_bits_oldVd_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs1_0 <= io_in_bits_vs1_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs1_1 <= io_in_bits_vs1_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs1_2 <= io_in_bits_vs1_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs1_3 <= io_in_bits_vs1_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs2_0 <= io_in_bits_vs2_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs2_1 <= io_in_bits_vs2_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs2_2 <= io_in_bits_vs2_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vs2_3 <= io_in_bits_vs2_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_scalarFpData <= io_in_bits_scalarFpData;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_funct6 <= io_in_bits_funct6;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_operandType <= io_in_bits_operandType;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
      inputBits_vm <= io_in_bits_vm;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30
    end
    if (candidateReady & inputValid) begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:72:35, :75:34, :79:48, :179:24, :181:22, :182:28
      candidateBits_warpId <= inputBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_pc <= inputBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_warpActiveMask <= inputBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_vd <= inputBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_funct6 <= inputBits_funct6;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_vm <= inputBits_vm;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_scalarFpData <= inputBits_scalarFpData;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_oldVd_0 <= inputBits_oldVd_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_oldVd_1 <= inputBits_oldVd_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_oldVd_2 <= inputBits_oldVd_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_oldVd_3 <= inputBits_oldVd_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_lhs_0 <= inputBits_vs2_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_lhs_1 <= inputBits_vs2_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_lhs_2 <= inputBits_vs2_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_lhs_3 <= inputBits_vs2_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_rhs_0 <= rhs;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :196:22
      candidateBits_rhs_1 <= rhs_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :196:22
      candidateBits_rhs_2 <= rhs_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :196:22
      candidateBits_rhs_3 <= rhs_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :196:22
      candidateBits_enabled <= inputBits_activeMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_rawActiveMask <= inputBits_rawActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_predicateMask <= inputBits_predicateMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34
      candidateBits_lhsLess_0 <=
        _candidateBits_equal_0_T_1
          ? (inputBits_vs2_0[31] ? _lhsGreater_T_2 : _lhsGreater_T_1)
          : inputBits_vs2_0[31] & ~(rhs[31]);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :205:26, :206:23, :207:{14,35,52}, :208:{23,26}
      candidateBits_lhsLess_1 <=
        _candidateBits_equal_1_T_1
          ? (inputBits_vs2_1[31] ? _lhsGreater_T_8 : _lhsGreater_T_7)
          : inputBits_vs2_1[31] & ~(rhs_1[31]);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :205:26, :206:23, :207:{14,35,52}, :208:{23,26}
      candidateBits_lhsLess_2 <=
        _candidateBits_equal_2_T_1
          ? (inputBits_vs2_2[31] ? _lhsGreater_T_14 : _lhsGreater_T_13)
          : inputBits_vs2_2[31] & ~(rhs_2[31]);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :205:26, :206:23, :207:{14,35,52}, :208:{23,26}
      candidateBits_lhsLess_3 <=
        _candidateBits_equal_3_T_1
          ? (inputBits_vs2_3[31] ? _lhsGreater_T_20 : _lhsGreater_T_19)
          : inputBits_vs2_3[31] & ~(rhs_3[31]);	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :205:26, :206:23, :207:{14,35,52}, :208:{23,26}
      candidateBits_lhsGreater_0 <=
        _candidateBits_equal_0_T_1
          ? (inputBits_vs2_0[31] ? _lhsGreater_T_1 : _lhsGreater_T_2)
          : ~(inputBits_vs2_0[31]) & rhs[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :206:23, :207:{35,52}, :210:29, :212:14, :213:{11,24}
      candidateBits_lhsGreater_1 <=
        _candidateBits_equal_1_T_1
          ? (inputBits_vs2_1[31] ? _lhsGreater_T_7 : _lhsGreater_T_8)
          : ~(inputBits_vs2_1[31]) & rhs_1[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :206:23, :207:{35,52}, :210:29, :212:14, :213:{11,24}
      candidateBits_lhsGreater_2 <=
        _candidateBits_equal_2_T_1
          ? (inputBits_vs2_2[31] ? _lhsGreater_T_13 : _lhsGreater_T_14)
          : ~(inputBits_vs2_2[31]) & rhs_2[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :206:23, :207:{35,52}, :210:29, :212:14, :213:{11,24}
      candidateBits_lhsGreater_3 <=
        _candidateBits_equal_3_T_1
          ? (inputBits_vs2_3[31] ? _lhsGreater_T_19 : _lhsGreater_T_20)
          : ~(inputBits_vs2_3[31]) & rhs_3[31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :201:30, :202:30, :206:23, :207:{35,52}, :210:29, :212:14, :213:{11,24}
      candidateBits_equal_0 <=
        inputBits_vs2_0[30:0] == rhs[30:0] & _candidateBits_equal_0_T_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :203:25, :204:25, :206:23, :221:{18,29}
      candidateBits_equal_1 <=
        inputBits_vs2_1[30:0] == rhs_1[30:0] & _candidateBits_equal_1_T_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :203:25, :204:25, :206:23, :221:{18,29}
      candidateBits_equal_2 <=
        inputBits_vs2_2[30:0] == rhs_2[30:0] & _candidateBits_equal_2_T_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :203:25, :204:25, :206:23, :221:{18,29}
      candidateBits_equal_3 <=
        inputBits_vs2_3[30:0] == rhs_3[30:0] & _candidateBits_equal_3_T_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :203:25, :204:25, :206:23, :221:{18,29}
      candidateBits_unordered_0 <=
        (&(inputBits_vs2_0[30:23])) & (|(inputBits_vs2_0[22:0])) | (&(rhs[30:23]))
        & (|(rhs[22:0]));	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :198:{14,23,34,40,48}, :200:{14,23,34,40,48}, :222:49
      candidateBits_unordered_1 <=
        (&(inputBits_vs2_1[30:23])) & (|(inputBits_vs2_1[22:0])) | (&(rhs_1[30:23]))
        & (|(rhs_1[22:0]));	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :198:{14,23,34,40,48}, :200:{14,23,34,40,48}, :222:49
      candidateBits_unordered_2 <=
        (&(inputBits_vs2_2[30:23])) & (|(inputBits_vs2_2[22:0])) | (&(rhs_2[30:23]))
        & (|(rhs_2[22:0]));	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :198:{14,23,34,40,48}, :200:{14,23,34,40,48}, :222:49
      candidateBits_unordered_3 <=
        (&(inputBits_vs2_3[30:23])) & (|(inputBits_vs2_3[22:0])) | (&(rhs_3[30:23]))
        & (|(rhs_3[22:0]));	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:73:30, :75:34, :196:22, :198:{14,23,34,40,48}, :200:{14,23,34,40,48}, :222:49
    end
    if (outputReady & candidateValid) begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:74:39, :77:31, :78:42, :162:21, :164:26, :165:25
      outputBits_warpId <= candidateBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31
      outputBits_pc <= candidateBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31
      outputBits_warpActiveMask <= candidateBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31
      outputBits_vd <= candidateBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31
      outputBits_data_0 <=
        isFpMerge
          ? (candidateBits_vm
               ? (candidateBits_enabled[0]
                    ? candidateBits_scalarFpData
                    : candidateBits_oldVd_0)
               : candidateBits_rawActiveMask[0] & candidateBits_predicateMask[0]
                   ? candidateBits_scalarFpData
                   : candidateBits_rawActiveMask[0]
                       ? candidateBits_lhs_0
                       : candidateBits_oldVd_0)
          : isCompare | ~(candidateBits_enabled[0])
              ? candidateBits_oldVd_0
              : isMinMax
                  ? (candidateBits_unordered_0
                       ? 32'h7FC00000
                       : (isMinMax & _minMaxData_T_15
                            ? candidateBits_lhsLess_0
                            : candidateBits_lhsGreater_0)
                           ? candidateBits_lhs_0
                           : candidateBits_rhs_0)
                  : _signData_T_51
                      ? {candidateBits_lhs_0[31] ^ candidateBits_rhs_0[31],
                         candidateBits_lhs_0[30:0]}
                      : _signData_T_49
                          ? {~(candidateBits_rhs_0[31]), candidateBits_lhs_0[30:0]}
                          : _signData_T_47
                              ? {candidateBits_rhs_0[31], candidateBits_lhs_0[30:0]}
                              : candidateBits_lhs_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :87:{26,38}, :89:37, :90:48, :95:40, :100:26, :101:26, :103:56, :104:{21,38}, :105:{21,22}, :106:{21,34}, :108:25, :111:10, :112:18, :113:12, :114:12, :126:24, :131:24, :133:10, :134:10, :135:{36,43,73}, :137:12, :144:26, :147:10
      outputBits_data_1 <=
        isFpMerge
          ? (candidateBits_vm
               ? (candidateBits_enabled[1]
                    ? candidateBits_scalarFpData
                    : candidateBits_oldVd_1)
               : candidateBits_rawActiveMask[1] & candidateBits_predicateMask[1]
                   ? candidateBits_scalarFpData
                   : candidateBits_rawActiveMask[1]
                       ? candidateBits_lhs_1
                       : candidateBits_oldVd_1)
          : isCompare | ~(candidateBits_enabled[1])
              ? candidateBits_oldVd_1
              : isMinMax
                  ? (candidateBits_unordered_1
                       ? 32'h7FC00000
                       : (isMinMax & _minMaxData_T_15
                            ? candidateBits_lhsLess_1
                            : candidateBits_lhsGreater_1)
                           ? candidateBits_lhs_1
                           : candidateBits_rhs_1)
                  : _signData_T_51
                      ? {candidateBits_lhs_1[31] ^ candidateBits_rhs_1[31],
                         candidateBits_lhs_1[30:0]}
                      : _signData_T_49
                          ? {~(candidateBits_rhs_1[31]), candidateBits_lhs_1[30:0]}
                          : _signData_T_47
                              ? {candidateBits_rhs_1[31], candidateBits_lhs_1[30:0]}
                              : candidateBits_lhs_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :87:{26,38}, :89:37, :90:48, :95:40, :100:26, :101:26, :103:56, :104:{21,38}, :105:{21,22}, :106:{21,34}, :108:25, :111:10, :112:18, :113:12, :114:12, :126:24, :131:24, :133:10, :134:10, :135:{36,43,73}, :137:12, :144:26, :147:10
      outputBits_data_2 <=
        isFpMerge
          ? (candidateBits_vm
               ? (candidateBits_enabled[2]
                    ? candidateBits_scalarFpData
                    : candidateBits_oldVd_2)
               : candidateBits_rawActiveMask[2] & candidateBits_predicateMask[2]
                   ? candidateBits_scalarFpData
                   : candidateBits_rawActiveMask[2]
                       ? candidateBits_lhs_2
                       : candidateBits_oldVd_2)
          : isCompare | ~(candidateBits_enabled[2])
              ? candidateBits_oldVd_2
              : isMinMax
                  ? (candidateBits_unordered_2
                       ? 32'h7FC00000
                       : (isMinMax & _minMaxData_T_15
                            ? candidateBits_lhsLess_2
                            : candidateBits_lhsGreater_2)
                           ? candidateBits_lhs_2
                           : candidateBits_rhs_2)
                  : _signData_T_51
                      ? {candidateBits_lhs_2[31] ^ candidateBits_rhs_2[31],
                         candidateBits_lhs_2[30:0]}
                      : _signData_T_49
                          ? {~(candidateBits_rhs_2[31]), candidateBits_lhs_2[30:0]}
                          : _signData_T_47
                              ? {candidateBits_rhs_2[31], candidateBits_lhs_2[30:0]}
                              : candidateBits_lhs_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :87:{26,38}, :89:37, :90:48, :95:40, :100:26, :101:26, :103:56, :104:{21,38}, :105:{21,22}, :106:{21,34}, :108:25, :111:10, :112:18, :113:12, :114:12, :126:24, :131:24, :133:10, :134:10, :135:{36,43,73}, :137:12, :144:26, :147:10
      outputBits_data_3 <=
        isFpMerge
          ? (candidateBits_vm
               ? (candidateBits_enabled[3]
                    ? candidateBits_scalarFpData
                    : candidateBits_oldVd_3)
               : candidateBits_rawActiveMask[3] & candidateBits_predicateMask[3]
                   ? candidateBits_scalarFpData
                   : candidateBits_rawActiveMask[3]
                       ? candidateBits_lhs_3
                       : candidateBits_oldVd_3)
          : isCompare | ~(candidateBits_enabled[3])
              ? candidateBits_oldVd_3
              : isMinMax
                  ? (candidateBits_unordered_3
                       ? 32'h7FC00000
                       : (isMinMax & _minMaxData_T_15
                            ? candidateBits_lhsLess_3
                            : candidateBits_lhsGreater_3)
                           ? candidateBits_lhs_3
                           : candidateBits_rhs_3)
                  : _signData_T_51
                      ? {candidateBits_lhs_3[31] ^ candidateBits_rhs_3[31],
                         candidateBits_lhs_3[30:0]}
                      : _signData_T_49
                          ? {~(candidateBits_rhs_3[31]), candidateBits_lhs_3[30:0]}
                          : _signData_T_47
                              ? {candidateBits_rhs_3[31], candidateBits_lhs_3[30:0]}
                              : candidateBits_lhs_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :87:{26,38}, :89:37, :90:48, :95:40, :100:26, :101:26, :103:56, :104:{21,38}, :105:{21,22}, :106:{21,34}, :108:25, :111:10, :112:18, :113:12, :114:12, :126:24, :131:24, :133:10, :134:10, :135:{36,43,73}, :137:12, :144:26, :147:10
      outputBits_mask <=
        {candidateBits_enabled[3]
           & (_comparison_T_61
                ? candidateBits_lhsGreater_3 | candidateBits_equal_3
                : _comparison_T_59
                    ? candidateBits_lhsGreater_3
                    : _comparison_T_57
                        ? ~candidateBits_equal_3
                        : _comparison_T_55
                            ? candidateBits_lhsLess_3
                            : _comparison_T_53
                                ? candidateBits_lhsLess_3 | candidateBits_equal_3
                                : _comparison_T_51 & candidateBits_equal_3)
           & ~candidateBits_unordered_3,
         candidateBits_enabled[2]
           & (_comparison_T_61
                ? candidateBits_lhsGreater_2 | candidateBits_equal_2
                : _comparison_T_59
                    ? candidateBits_lhsGreater_2
                    : _comparison_T_57
                        ? ~candidateBits_equal_2
                        : _comparison_T_55
                            ? candidateBits_lhsLess_2
                            : _comparison_T_53
                                ? candidateBits_lhsLess_2 | candidateBits_equal_2
                                : _comparison_T_51 & candidateBits_equal_2)
           & ~candidateBits_unordered_2,
         candidateBits_enabled[1]
           & (_comparison_T_61
                ? candidateBits_lhsGreater_1 | candidateBits_equal_1
                : _comparison_T_59
                    ? candidateBits_lhsGreater_1
                    : _comparison_T_57
                        ? ~candidateBits_equal_1
                        : _comparison_T_55
                            ? candidateBits_lhsLess_1
                            : _comparison_T_53
                                ? candidateBits_lhsLess_1 | candidateBits_equal_1
                                : _comparison_T_51 & candidateBits_equal_1)
           & ~candidateBits_unordered_1,
         candidateBits_enabled[0]
           & (_comparison_T_61
                ? candidateBits_lhsGreater_0 | candidateBits_equal_0
                : _comparison_T_59
                    ? candidateBits_lhsGreater_0
                    : _comparison_T_57
                        ? ~candidateBits_equal_0
                        : _comparison_T_55
                            ? candidateBits_lhsLess_0
                            : _comparison_T_53
                                ? candidateBits_lhsLess_0 | candidateBits_equal_0
                                : _comparison_T_51 & candidateBits_equal_0)
           & ~candidateBits_unordered_0};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :95:40, :117:62, :119:27, :121:18, :123:30, :124:{8,11}, :153:31, :170:35
      outputBits_writesMask <= isCompare;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31, :89:37
      outputBits_flags <=
        {candidateBits_enabled[0] & candidateBits_unordered_0 & _outputBits_writesFlags_T
           | candidateBits_enabled[1] & candidateBits_unordered_1
           & _outputBits_writesFlags_T | candidateBits_enabled[2]
           & candidateBits_unordered_2 & _outputBits_writesFlags_T
           | candidateBits_enabled[3] & candidateBits_unordered_3
           & _outputBits_writesFlags_T,
         4'h0};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:75:34, :77:31, :95:40, :155:{15,28,41}, :174:{12,32}
      outputBits_writesFlags <= _outputBits_writesFlags_T;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:77:31, :155:41
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:36];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
    initial begin	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
        for (logic [5:0] i = 6'h0; i < 6'h25; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
        end	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
        inputValid = _RANDOM[6'h0][0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :72:35
        inputBits_warpId = _RANDOM[6'h0][2:1];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :72:35, :73:30
        inputBits_pc = {_RANDOM[6'h0][31:3], _RANDOM[6'h1][2:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :72:35, :73:30
        inputBits_warpActiveMask = _RANDOM[6'h1][6:3];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vd = _RANDOM[6'h1][11:7];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_activeMask = _RANDOM[6'h1][15:12];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_rawActiveMask = _RANDOM[6'h1][19:16];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_predicateMask = _RANDOM[6'h1][23:20];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_oldVd_0 = {_RANDOM[6'h1][31:24], _RANDOM[6'h2][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_oldVd_1 = {_RANDOM[6'h2][31:24], _RANDOM[6'h3][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_oldVd_2 = {_RANDOM[6'h3][31:24], _RANDOM[6'h4][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_oldVd_3 = {_RANDOM[6'h4][31:24], _RANDOM[6'h5][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs1_0 = {_RANDOM[6'h5][31:24], _RANDOM[6'h6][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs1_1 = {_RANDOM[6'h6][31:24], _RANDOM[6'h7][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs1_2 = {_RANDOM[6'h7][31:24], _RANDOM[6'h8][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs1_3 = {_RANDOM[6'h8][31:24], _RANDOM[6'h9][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs2_0 = {_RANDOM[6'h9][31:24], _RANDOM[6'hA][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs2_1 = {_RANDOM[6'hA][31:24], _RANDOM[6'hB][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs2_2 = {_RANDOM[6'hB][31:24], _RANDOM[6'hC][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vs2_3 = {_RANDOM[6'hC][31:24], _RANDOM[6'hD][23:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_scalarFpData = {_RANDOM[6'hD][31:29], _RANDOM[6'hE][28:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_funct6 = _RANDOM[6'hF][5:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_operandType = _RANDOM[6'hF][8:6];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        inputBits_vm = _RANDOM[6'hF][9];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30
        candidateValid = _RANDOM[6'hF][10];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30, :74:39
        candidateBits_warpId = _RANDOM[6'hF][12:11];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30, :75:34
        candidateBits_pc = {_RANDOM[6'hF][31:13], _RANDOM[6'h10][12:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :73:30, :75:34
        candidateBits_warpActiveMask = _RANDOM[6'h10][16:13];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_vd = _RANDOM[6'h10][21:17];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_funct6 = _RANDOM[6'h10][27:22];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_vm = _RANDOM[6'h10][31];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_scalarFpData = _RANDOM[6'h11];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_oldVd_0 = _RANDOM[6'h12];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_oldVd_1 = _RANDOM[6'h13];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_oldVd_2 = _RANDOM[6'h14];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_oldVd_3 = _RANDOM[6'h15];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhs_0 = _RANDOM[6'h16];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhs_1 = _RANDOM[6'h17];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhs_2 = _RANDOM[6'h18];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhs_3 = _RANDOM[6'h19];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_rhs_0 = _RANDOM[6'h1A];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_rhs_1 = _RANDOM[6'h1B];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_rhs_2 = _RANDOM[6'h1C];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_rhs_3 = _RANDOM[6'h1D];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_enabled = _RANDOM[6'h1E][3:0];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_rawActiveMask = _RANDOM[6'h1E][7:4];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_predicateMask = _RANDOM[6'h1E][11:8];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsLess_0 = _RANDOM[6'h1E][12];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsLess_1 = _RANDOM[6'h1E][13];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsLess_2 = _RANDOM[6'h1E][14];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsLess_3 = _RANDOM[6'h1E][15];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsGreater_0 = _RANDOM[6'h1E][16];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsGreater_1 = _RANDOM[6'h1E][17];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsGreater_2 = _RANDOM[6'h1E][18];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_lhsGreater_3 = _RANDOM[6'h1E][19];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_equal_0 = _RANDOM[6'h1E][20];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_equal_1 = _RANDOM[6'h1E][21];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_equal_2 = _RANDOM[6'h1E][22];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_equal_3 = _RANDOM[6'h1E][23];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_unordered_0 = _RANDOM[6'h1E][24];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_unordered_1 = _RANDOM[6'h1E][25];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_unordered_2 = _RANDOM[6'h1E][26];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        candidateBits_unordered_3 = _RANDOM[6'h1E][27];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34
        outputValid = _RANDOM[6'h1E][28];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :76:36
        outputBits_warpId = _RANDOM[6'h1E][30:29];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :77:31
        outputBits_pc = {_RANDOM[6'h1E][31], _RANDOM[6'h1F][30:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :75:34, :77:31
        outputBits_warpActiveMask = {_RANDOM[6'h1F][31], _RANDOM[6'h20][2:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_vd = _RANDOM[6'h20][7:3];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_data_0 = {_RANDOM[6'h20][31:8], _RANDOM[6'h21][7:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_data_1 = {_RANDOM[6'h21][31:8], _RANDOM[6'h22][7:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_data_2 = {_RANDOM[6'h22][31:8], _RANDOM[6'h23][7:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_data_3 = {_RANDOM[6'h23][31:8], _RANDOM[6'h24][7:0]};	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_mask = _RANDOM[6'h24][11:8];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_writesMask = _RANDOM[6'h24][12];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_flags = _RANDOM[6'h24][18:14];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
        outputBits_writesFlags = _RANDOM[6'h24][19];	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = inputReady;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :80:40
  assign io_out_valid = outputValid;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :76:36
  assign io_out_bits_warpId = outputBits_warpId;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_pc = outputBits_pc;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_warpActiveMask = outputBits_warpActiveMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_vd = outputBits_vd;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_data_0 = outputBits_data_0;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_data_1 = outputBits_data_1;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_data_2 = outputBits_data_2;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_data_3 = outputBits_data_3;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_mask = outputBits_mask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_writesMask = outputBits_writesMask;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_flags = outputBits_flags;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
  assign io_out_bits_writesFlags = outputBits_writesFlags;	// src/main/scala/opengpu/core/vector/VectorFpuAlu.scala:66:7, :77:31
endmodule

