// Generated by CIRCT firtool-1.133.0
`ifndef layers_ScalarBackend_Verification_Assert	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `define layers_ScalarBackend_Verification_Assert
  `include "layers-ScalarBackend-Verification.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-ScalarIssueStage-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-ScalarExecutionDispatch-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-IntegerExecuteStage-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-MultiplyExecuteStage-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-DivideExecuteStage-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
  `include "layers-ScalarCommitStage-Verification-Assert.sv"	// src/main/scala/opengpu/core/backend/ScalarBackend.scala:36:7
`endif // not def layers_ScalarBackend_Verification_Assert
