// Generated by CIRCT firtool-1.133.0
`ifndef layers_VectorDataCache_Verification_Assert	// src/main/scala/opengpu/core/memory/VectorDataCache.scala:35:7
  `define layers_VectorDataCache_Verification_Assert
  `include "layers-VectorDataCache-Verification.sv"	// src/main/scala/opengpu/core/memory/VectorDataCache.scala:35:7
  bind VectorDataCache VectorDataCache_Verification_Assert verification_assert ();
`endif // not def layers_VectorDataCache_Verification_Assert
