// Generated by CIRCT firtool-1.133.0
`ifndef layers_FrontendScalarFpu_Verification_Assert	// src/main/scala/opengpu/core/frontend/FrontendScalarFpu.scala:23:7
  `define layers_FrontendScalarFpu_Verification_Assert
  `include "layers-FrontendScalarFpu-Verification.sv"	// src/main/scala/opengpu/core/frontend/FrontendScalarFpu.scala:23:7
  `include "layers-FrontendICache-Verification-Assert.sv"	// src/main/scala/opengpu/core/frontend/FrontendScalarFpu.scala:23:7
  `include "layers-ScalarBackend-Verification-Assert.sv"	// src/main/scala/opengpu/core/frontend/FrontendScalarFpu.scala:23:7
  `include "layers-FpuBackend-Verification-Assert.sv"	// src/main/scala/opengpu/core/frontend/FrontendScalarFpu.scala:23:7
`endif // not def layers_FrontendScalarFpu_Verification_Assert
