// Generated by CIRCT firtool-1.133.0
`ifndef layers_GpuHostAxi_Verification_Cover	// src/main/scala/opengpu/graphics/GpuHostAxi.scala:35:7
  `define layers_GpuHostAxi_Verification_Cover
  `include "layers-GpuHostAxi-Verification.sv"	// src/main/scala/opengpu/graphics/GpuHostAxi.scala:35:7
`endif // not def layers_GpuHostAxi_Verification_Cover
